/**
 * Java parity:
 * - AI/src/features/Feature.java
 * - AI/src/features/feature_sets/BaseFeatureSet.java
 *
 * A `Feature` maps a (Context, candidate Move) pair to a real-valued
 * activation. The Java side ships a sprawling feature library
 * (geometric, pattern, spatial) generated by feature discovery; this TS
 * port keeps the abstraction and provides a small starter set of
 * geometric features so downstream code (e.g. a softmax policy or
 * decision tree) has something concrete to compose.
 */

import type { Context } from "../context.js";
import type { Move } from "../move.js";

export interface Feature {
  readonly name: string;
  activation(context: Context, move: Move): number;
}

/** Sum the named subset of features for a (context, move). */
export class FeatureSet {
  public readonly features: readonly Feature[];

  public constructor(features: readonly Feature[]) {
    this.features = features;
  }

  /** Linear combination of activations × weights. */
  public dot(context: Context, move: Move, weights: readonly number[]): number {
    let total = 0;
    for (let i = 0; i < this.features.length; i += 1) {
      const w = weights[i] ?? 0;
      if (w === 0) continue;
      const f = this.features[i];
      if (!f) continue;
      total += w * f.activation(context, move);
    }
    return total;
  }

  /** Vector of activations, one per feature. */
  public extract(context: Context, move: Move): number[] {
    const out: number[] = new Array(this.features.length);
    for (let i = 0; i < this.features.length; i += 1) {
      const f = this.features[i];
      out[i] = f ? f.activation(context, move) : 0;
    }
    return out;
  }
}

// ---- Built-in geometric features ------------------------------------------

/** 1 if the move targets a corner of an N×N flat board, else 0. */
export class CornerFeature implements Feature {
  public readonly name = "is-corner";

  public activation(context: Context, move: Move): number {
    const site = move.siteIndices[0];
    if (site === undefined) return 0;
    const game = context.game as { width?: number; height?: number };
    const w = game.width ?? 0;
    const h = game.height ?? 0;
    if (w <= 0 || h <= 0) return 0;
    const x = site % w;
    const y = Math.floor(site / w);
    if ((x === 0 || x === w - 1) && (y === 0 || y === h - 1)) return 1;
    return 0;
  }
}

/** 1 if the move targets the geometric centre of the board (odd-sized), else 0. */
export class CentreFeature implements Feature {
  public readonly name = "is-centre";

  public activation(context: Context, move: Move): number {
    const site = move.siteIndices[0];
    if (site === undefined) return 0;
    const game = context.game as { width?: number; height?: number };
    const w = game.width ?? 0;
    const h = game.height ?? 0;
    if (w <= 0 || h <= 0) return 0;
    if (w % 2 === 0 || h % 2 === 0) return 0;
    const cx = Math.floor(w / 2);
    const cy = Math.floor(h / 2);
    return site === cy * w + cx ? 1 : 0;
  }
}

/** Activation = number of friendly orthogonal neighbours of the target site. */
export class FriendlyNeighbourCountFeature implements Feature {
  public readonly name = "friendly-neighbours";

  public activation(context: Context, move: Move): number {
    const site = move.siteIndices[0];
    if (site === undefined) return 0;
    const game = context.game as { width?: number; height?: number };
    const w = game.width ?? 0;
    const h = game.height ?? 0;
    if (w <= 0 || h <= 0) return 0;
    const x = site % w;
    const y = Math.floor(site / w);
    const mover = move.mover;
    let count = 0;
    const offsets: readonly [number, number][] = [
      [1, 0],
      [-1, 0],
      [0, 1],
      [0, -1],
    ];
    for (const [dx, dy] of offsets) {
      const nx = x + dx;
      const ny = y + dy;
      if (nx < 0 || nx >= w || ny < 0 || ny >= h) continue;
      const cell = context.state.cellAt(ny * w + nx);
      if (cell.owner === mover) count += 1;
    }
    return count;
  }
}

/** A small starter feature set useful for square-board games. */
export function defaultGeometricFeatures(): FeatureSet {
  return new FeatureSet([
    new CornerFeature(),
    new CentreFeature(),
    new FriendlyNeighbourCountFeature(),
  ]);
}
