// @java ViewController/src/view/component/custom/types/ShogiType.java

/**
 * Shogi types.
 *
 * Faithful 1:1 port of view.component.custom.types.ShogiType.
 *
 * @author Matthew.Stephenson and Eric Piette (Java original)
 */
export class ShogiType {
  static readonly KING               = new ShogiType("玉将", "gyokushō",            "King");
  static readonly PRINCE             = new ShogiType("太子", "taishi",              "Prince");
  static readonly GOLDGENERAL        = new ShogiType("金将", "kinshō",              "Gold general");
  static readonly RIGHTGENERAL       = new ShogiType("右将", "ushō",               "Right general");
  static readonly RIGHTARMY          = new ShogiType("右軍", "ugun",               "Right army");
  static readonly LEFTGENERAL        = new ShogiType("左将", "sashō",              "Left general");
  static readonly LEFTARMY           = new ShogiType("左軍", "sagun",              "Left army");
  static readonly REARSTANDARD       = new ShogiType("後旗", "kōki",               "Rear standard");
  static readonly QUEEN              = new ShogiType("奔王", "honnō",              "Queen");
  static readonly FREEDREAMEATER     = new ShogiType("奔獏", "honbaku",            "Free dream-eater");
  static readonly WOODENDOVE         = new ShogiType("鳩槃", "kyūhan",             "Wooden dove");
  static readonly CERAMICDOVE        = new ShogiType("鳩盤", "kyūban",             "Ceramic dove");
  static readonly EARTHDRAGON        = new ShogiType("地龍", "chiryū",             "Earth dragon");
  static readonly FREEDEMON          = new ShogiType("奔鬼", "honki",              "Free demon");
  static readonly RUNNINGHORSE       = new ShogiType("走馬", "sōma",               "Running horse");
  static readonly BEASTCADET         = new ShogiType("獣曹", "jūsō",               "Beast cadet");
  static readonly LONGNOSEDGOBLIN    = new ShogiType("天狗", "tengu",              "Long-nosed goblin");
  static readonly MOUNTAINEAGLELEFT  = new ShogiType("山鷲鷲","sanshū left",       "Mountain eagle left");
  static readonly MOUNTAINEAGLERIGHT = new ShogiType("山鷲山","sanshū right",      "Mountain eagle right");
  static readonly FIREDEMON          = new ShogiType("火鬼", "kaki",               "Fire demon");
  static readonly FREEFIRE           = new ShogiType("奔火", "honka",              "Free fire");
  static readonly WHALE              = new ShogiType("鯨鯢", "keigei",             "Whale");
  static readonly GREATWHALE         = new ShogiType("大鯨", "daigei",             "Great whale");
  static readonly RUNNINGRABBIT      = new ShogiType("走兎", "sōto",               "Running rabbit");
  static readonly WHITETIGER         = new ShogiType("白虎", "byakko",             "White tiger");
  static readonly DIVINETIGER        = new ShogiType("神虎", "shinko",             "Divine tiger");
  static readonly TURTLESNAKE        = new ShogiType("玄武", "genbu",              "Turtle-snake");
  static readonly DIVINETURTLE       = new ShogiType("神亀", "shinki",             "Divine turtle");
  static readonly LANCE              = new ShogiType("香車", "kyōsha",             "Lance");
  static readonly REVERSECHARIOT     = new ShogiType("反車", "hensha",             "Reverse chariot");
  static readonly FRAGRANTELEPHANT   = new ShogiType("香象", "kōzō",              "Fragrant elephant");
  static readonly ELEPHANTKING       = new ShogiType("象王", "zōō",               "Elephant king");
  static readonly WHITEELEPHANT      = new ShogiType("白象", "hakuzō",            "White elephant");
  static readonly TURTLEDOVE         = new ShogiType("山鳩", "sankyū",            "Turtle dove");
  static readonly FLYINGSWALLOW      = new ShogiType("飛燕", "hien",              "Flying swallow");
  static readonly CAPTIVEOFFICER     = new ShogiType("禽吏", "kinri",             "Captive officer");
  static readonly CAPTIVEBIRD        = new ShogiType("禽鳥", "kinchō",            "Captive bird");
  static readonly RAINDRAGON         = new ShogiType("雨龍", "uryū",              "Rain dragon");
  static readonly FORESTDEMON        = new ShogiType("森鬼", "shinki",            "Forest demon");
  static readonly THUNDERRUNNER      = new ShogiType("雷走", "raisō",             "Thunder runner");
  static readonly MOUNTAINSTAG       = new ShogiType("山鹿", "sanroku",           "Mountain stag");
  static readonly RUNNINGPUP         = new ShogiType("走狗", "sōku",              "Running pup");
  static readonly FREELEOPARD        = new ShogiType("奔豹", "honpyō",            "Free leopard");
  static readonly RUNNINGSERPENT     = new ShogiType("走蛇", "sōja",              "Running serpent");
  static readonly FREESERPENT        = new ShogiType("奔蛇", "honja",             "Free serpent");
  static readonly SIDESERPENT        = new ShogiType("横蛇", "ōja",               "Side serpent");
  static readonly GREATSHARK         = new ShogiType("大鱗", "dairin",            "Great shark");
  static readonly GREATDOVE          = new ShogiType("大鳩", "daikyū",            "Great dove");
  static readonly RUNNINGTIGER       = new ShogiType("走虎", "sōko",              "Running tiger");
  static readonly FREETIGER          = new ShogiType("奔虎", "honko",             "Free tiger");
  static readonly RUNNINGBEAR        = new ShogiType("走熊", "sōyū",              "Running bear");
  static readonly FREEBEAR           = new ShogiType("奔熊", "hon'yū",            "Free bear");
  static readonly YAKSHA             = new ShogiType("夜叉", "yasha",             "Yaksha");
  static readonly HEAVENLYTETRARCH   = new ShogiType("四天", "shiten",            "Heavenly Tetrarch");
  static readonly BUDDHISTDEVIL      = new ShogiType("羅刹", "rasetsu",           "Buddhist devil");
  static readonly GUARDIANOFTHEGODS  = new ShogiType("金剛", "kongō",             "Guardian of the Gods");
  static readonly WRESTLER           = new ShogiType("力士", "rikishi",           "Wrestler");
  static readonly SILVERGENERAL      = new ShogiType("銀将", "ginshō",            "Silver general");
  static readonly DRUNKENELEPHANT    = new ShogiType("酔象", "suizō",             "Drunken elephant");
  static readonly NEIGHBORINGKING    = new ShogiType("近王", "kinnō",             "Neighboring king");
  static readonly GOLDCHARIOT        = new ShogiType("金車", "kinsha",            "Gold chariot");
  static readonly PLAYFULCOCKATOO    = new ShogiType("遊母", "yūmo",              "Playful cockatoo");
  static readonly SIDEDRAGON         = new ShogiType("横龍", "ōryū",              "Side dragon");
  static readonly RUNNINGDRAGON      = new ShogiType("走龍", "sōryū",             "Running dragon");
  static readonly RUNNINGSTAG        = new ShogiType("走鹿", "sōroku",            "Running stag");
  static readonly FREESTAG           = new ShogiType("奔鹿", "honroku",           "Free stag");
  static readonly RUNNINGWOLF        = new ShogiType("走狼", "sōrō",              "Running wolf");
  static readonly FREEWOLF           = new ShogiType("奔狼", "honrō",             "Free wolf");
  static readonly BISHOPGENERAL      = new ShogiType("角将", "kakushō",           "Bishop general");
  static readonly RAINDEMON          = new ShogiType("霖鬼", "rinki",             "Rain demon");
  static readonly ROOKGENERAL        = new ShogiType("飛将", "hishō",             "Rook general");
  static readonly FLYINGCROCODILE    = new ShogiType("飛鰐", "higaku",            "Flying crocodile");
  static readonly RIGHTTIGER         = new ShogiType("右虎", "uko",               "Right tiger");
  static readonly LEFTTIGER          = new ShogiType("左虎", "sako",              "Left tiger");
  static readonly RIGHTDRAGON        = new ShogiType("右龍", "uryū",              "Right dragon");
  static readonly LEFTDRAGON         = new ShogiType("左龍", "saryū",             "Left dragon");
  static readonly BEASTOFFICER       = new ShogiType("獣吏", "jūri",              "Beast officer");
  static readonly BEASTBIRD          = new ShogiType("獣鳥", "jūchō",             "Beast bird");
  static readonly WINDDRAGON         = new ShogiType("風龍", "fūryū",             "Wind dragon");
  static readonly FREEDRAGON         = new ShogiType("奔龍", "honryū",            "Free dragon");
  static readonly FREEPUP            = new ShogiType("奔狗", "honku",             "Free pup");
  static readonly FREEDOG            = new ShogiType("奔犬", "honken",            "Free dog");
  static readonly RUSHINGBIRD        = new ShogiType("行鳥", "gyōchō",            "Rushing bird");
  static readonly OLDKITE            = new ShogiType("古鵄", "kotetsu",           "Old kite");
  static readonly PEACOCK            = new ShogiType("孔雀", "kujaku",            "Peacock");
  static readonly WATERDRAGON        = new ShogiType("水龍", "suiryū",            "Water dragon");
  static readonly FIREDRAGON         = new ShogiType("火龍", "karyū",             "Fire dragon");
  static readonly COPPERGENERAL      = new ShogiType("銅将", "dōshō",             "Copper general");
  static readonly PHOENIXMASTER      = new ShogiType("鳳師", "hōshi",             "Phoenix master");
  static readonly KIRINMASTER        = new ShogiType("麟師", "rinshi",            "Kirin master");
  static readonly SILVERCHARIOT      = new ShogiType("銀車", "ginsha",            "Silver chariot");
  static readonly GOOSEWING          = new ShogiType("鴻翼", "kōyoko",            "Goose wing");
  static readonly VERTICALBEAR       = new ShogiType("竪熊", "shuyū",             "Vertical bear");
  static readonly KNIGHT             = new ShogiType("桂馬", "keima",             "Knight");
  static readonly PIGGENERAL         = new ShogiType("豚将", "tonshō",            "Pig general");
  static readonly FREEPIG            = new ShogiType("奔豚", "honton",            "Free pig");
  static readonly CHICKENGENERAL     = new ShogiType("鶏将", "keishō",            "Chicken general");
  static readonly FREECHICKEN        = new ShogiType("奔鶏", "honkei",            "Free chicken");
  static readonly PUPGENERAL         = new ShogiType("狗将", "kushō",             "Pup general");
  static readonly HORSEGENERAL       = new ShogiType("馬将", "bashō",             "Horse general");
  static readonly FREEHORSE          = new ShogiType("奔馬", "honba",             "Free horse");
  static readonly OXGENERAL          = new ShogiType("牛将", "gyūshō",            "Ox general");
  static readonly FREEOX             = new ShogiType("奔牛", "hongyū",            "Free ox");
  static readonly CENTERSTANDARD     = new ShogiType("中旗", "chūki",             "Center standard");
  static readonly SIDEBOAR           = new ShogiType("横猪", "ōcho",              "Side boar");
  static readonly FREEBOAR           = new ShogiType("奔猪", "honcho",            "Free boar");
  static readonly SILVERRABBIT       = new ShogiType("銀兎", "ginto",             "Silver rabbit");
  static readonly GOLDENDEER         = new ShogiType("金鹿", "konroku",           "Golden deer");
  static readonly LION               = new ShogiType("獅子", "shishi",            "Lion");
  static readonly FURIOUSFIEND       = new ShogiType("奮迅", "funjin",            "Furious fiend");
  static readonly CAPTIVECADET       = new ShogiType("禽曹", "kinsō",             "Captive cadet");
  static readonly GREATSTAG          = new ShogiType("大鹿", "dairoku",           "Great stag");
  static readonly VIOLENTDRAGON      = new ShogiType("猛龍", "mōryū",             "Violent dragon");
  static readonly WOODLANDDEMON      = new ShogiType("林鬼", "rinki",             "Woodland demon");
  static readonly RIGHTPHOENIX       = new ShogiType("右鵰", "ushū",              "Right phoenix");
  static readonly VICEGENERAL        = new ShogiType("副将", "fukushō",           "Vice general");
  static readonly GREATGENERAL       = new ShogiType("大将", "taishō",            "Great general");
  static readonly STONECHARIOT       = new ShogiType("石車", "sekisha",           "Stone chariot");
  static readonly WALKINGHERON       = new ShogiType("歩振", "fushin",            "Walking heron");
  static readonly CLOUDEAGLE         = new ShogiType("雲鷲", "unjū",              "Cloud eagle");
  static readonly STRONGEAGLE        = new ShogiType("勁鷲", "keijū",             "Strong eagle");
  static readonly BISHOP             = new ShogiType("角行", "kakugyō",           "Bishop");
  static readonly ROOK               = new ShogiType("飛車", "hisha",             "Rook");
  static readonly SIDEWOLF           = new ShogiType("横狼", "ōrō",               "Side wolf");
  static readonly FLYINGCAT          = new ShogiType("飛猫", "hibyō",             "Flying cat");
  static readonly MOUNTAINFALCON     = new ShogiType("山鷹", "san'ō",             "Mountain falcon");
  static readonly VERTICALTIGER      = new ShogiType("竪虎", "shuko",             "Vertical tiger");
  static readonly SOLDIER            = new ShogiType("兵士", "heishi",            "Soldier");
  static readonly CAVALIER           = new ShogiType("騎士", "kishi",             "Cavalier");
  static readonly LITTLESTANDARD     = new ShogiType("小旗", "shōki",             "Little standard");
  static readonly CLOUDDRAGON        = new ShogiType("雲龍", "unryū",             "Cloud dragon");
  static readonly COPPERCHARIOT      = new ShogiType("銅車", "dōsha",             "Copper chariot");
  static readonly COPPERELEPHANT     = new ShogiType("銅象", "dōzō",              "Copper elephant");
  static readonly RUNNINGCHARIOT     = new ShogiType("走車", "sōsha",             "Running chariot");
  static readonly BURNINGCHARIOT     = new ShogiType("炮車", "hōsha",             "Burning chariot");
  static readonly RAMSHEADSOLDIER    = new ShogiType("羊兵", "yōhei",             "Ram's-head soldier");
  static readonly TIGERSOLDIER       = new ShogiType("虎兵", "kohei",             "Tiger soldier");
  static readonly VIOLENTOX          = new ShogiType("猛牛", "mōgyū",             "Violent ox");
  static readonly GREATDRAGON        = new ShogiType("大龍", "dairyū",            "Great dragon");
  static readonly ANCIENTDRAGON      = new ShogiType("元龍", "genryū, ganryū",    "Ancient dragon");
  static readonly GOLDENBIRD         = new ShogiType("金翅", "kinshi",            "Golden bird");
  static readonly FREEBIRD           = new ShogiType("奔翅", "honshi",            "Free bird");
  static readonly DARKSPIRIT         = new ShogiType("無明", "mumyō",             "Dark spirit");
  static readonly BUDDHISTSPIRIT     = new ShogiType("法性", "hōsei",             "Buddhist spirit");
  static readonly DEVA               = new ShogiType("提婆", "daiba",             "Deva");
  static readonly TEACHINGKING       = new ShogiType("教王", "kyōō",              "Teaching king");
  static readonly WOODCHARIOT        = new ShogiType("木車", "mokusha",           "Wood chariot");
  static readonly WINDSNAPPINGTURTLE = new ShogiType("風鼈", "fūbetsu",           "Wind snapping turtle");
  static readonly WHITEHORSE         = new ShogiType("白駒", "hakku",             "White horse");
  static readonly GREATHORSE         = new ShogiType("大駒", "daiku",             "Great horse");
  static readonly HOWLINGDOG         = new ShogiType("駒犬", "kiken",             "Howling dog");
  static readonly RIGHTDOG           = new ShogiType("右犬", "uken",              "Right dog");
  static readonly LEFTDOG            = new ShogiType("左犬", "saken",             "Left dog");
  static readonly SIDEMOVER          = new ShogiType("横行", "ōgyō",              "Side mover");
  static readonly PRANCINGSTAG       = new ShogiType("踊鹿", "yōroku",            "Prancing stag");
  static readonly WATERBUFFALO       = new ShogiType("水牛", "suigyū",            "Water buffalo");
  static readonly GREATDREAMEATER    = new ShogiType("大獏", "daibaku",           "Great dream-eater");
  static readonly FEROCIOUSLEOPARD   = new ShogiType("猛豹", "mōhyō",             "Ferocious leopard");
  static readonly FIERCEEAGLE        = new ShogiType("猛鷲", "mōjū",              "Fierce eagle");
  static readonly FLYINGDRAGON       = new ShogiType("飛龍", "hiryū",             "Flying dragon");
  static readonly POISONOUSSNAKE     = new ShogiType("毒蛇", "dokuja",            "Poisonous snake");
  static readonly FLYINGGOOSE        = new ShogiType("鳫飛", "ganhi",             "Flying goose");
  static readonly STRUTTINGCROW      = new ShogiType("烏行", "ukō",               "Strutting crow");
  static readonly FLYINGFALCON       = new ShogiType("飛鷹", "hiyō",              "Flying falcon");
  static readonly BLINDDOG           = new ShogiType("盲犬", "mōken",             "Blind dog");
  static readonly WATERGENERAL       = new ShogiType("水将", "suishō",            "Water general");
  static readonly FIREGENERAL        = new ShogiType("火将", "kashō",             "Fire general");
  static readonly PHOENIX            = new ShogiType("鳳凰", "hōō",               "Phoenix");
  static readonly KIRIN              = new ShogiType("麒麟", "kirin",             "Kirin");
  static readonly HOOKMOVER          = new ShogiType("鉤行", "kōgyō",             "Hook mover");
  static readonly LITTLETURTLE       = new ShogiType("小亀", "shōki",             "Little turtle");
  static readonly TREASURETURTLE     = new ShogiType("宝亀", "hōki",              "Treasure turtle");
  static readonly GREATTURTLE        = new ShogiType("大亀", "daiki",             "Great turtle");
  static readonly SPIRITTURTLE       = new ShogiType("霊亀", "reiki",             "Spirit turtle");
  static readonly CAPRICORN          = new ShogiType("摩羯", "makatsu",           "Capricorn");
  static readonly TILECHARIOT        = new ShogiType("瓦車", "gasha",             "Tile chariot");
  static readonly RUNNINGTILE        = new ShogiType("走瓦", "sōga",              "Running tile");
  static readonly VERTICALWOLF       = new ShogiType("竪狼", "shurō",             "Vertical wolf");
  static readonly SIDEOX             = new ShogiType("横牛", "ōgyū",              "Side ox");
  static readonly DONKEY             = new ShogiType("驢馬", "roba",              "Donkey");
  static readonly FLYINGHORSE        = new ShogiType("馬麟", "barin",             "Flying horse");
  static readonly VIOLENTBEAR        = new ShogiType("猛熊", "mōyū",              "Violent bear");
  static readonly GREATBEAR          = new ShogiType("大熊", "daiyū",             "Great bear");
  static readonly ANGRYBOAR          = new ShogiType("嗔猪", "shincho",           "Angry boar");
  static readonly EVILWOLF           = new ShogiType("悪狼", "akurō",             "Evil wolf");
  static readonly VENOMOUSWOLF       = new ShogiType("毒狼", "dokurō",            "Venomous wolf");
  static readonly LIBERATEDHORSE     = new ShogiType("風馬", "fūma",              "Liberated horse");
  static readonly HEAVENLYHORSE      = new ShogiType("天馬", "temma",             "Heavenly horse");
  static readonly FLYINGCOCK         = new ShogiType("鶏飛", "keihi",             "Flying cock");
  static readonly RAIDINGFALCON      = new ShogiType("延鷹", "en'yō",             "Raiding falcon");
  static readonly OLDMONKEY          = new ShogiType("古猿", "koen",              "Old monkey");
  static readonly MOUNTAINWITCH      = new ShogiType("山母", "sanbo",             "Mountain witch");
  static readonly CHINESECOCK        = new ShogiType("淮鶏", "waikei",            "Chinese cock");
  static readonly WIZARDSTORK        = new ShogiType("仙鷦", "senkaku",           "Wizard stork");
  static readonly NORTHERNBARBARIAN  = new ShogiType("北狄", "hokuteki",          "Northern barbarian");
  static readonly SOUTHERNBARBARIAN  = new ShogiType("南蛮", "nanban",            "Southern barbarian");
  static readonly WESTERNBARBARIAN   = new ShogiType("西戎", "seijū",             "Western barbarian");
  static readonly EASTERNBARBARIAN   = new ShogiType("東夷", "tōi",               "Eastern barbarian");
  static readonly VIOLENTSTAG        = new ShogiType("猛鹿", "mōroku",            "Violent stag");
  static readonly RUSHINGBOAR        = new ShogiType("行猪", "gyōcho",            "Rushing boar");
  static readonly VIOLENTWOLF        = new ShogiType("猛狼", "mōrō",              "Violent wolf");
  static readonly BEARSEYES          = new ShogiType("熊眼", "yūgan",             "Bear's eyes");
  static readonly TREACHEROUSFOX     = new ShogiType("隠狐", "inko, onko",        "Treacherous fox");
  static readonly MOUNTAINCRANE      = new ShogiType("山鶻", "sankotsu",          "Mountain crane");
  static readonly CENTERMASTER       = new ShogiType("中師", "chūshi",            "Center master");
  static readonly ROCMASTER          = new ShogiType("鵬師", "hōshi",             "Roc master");
  static readonly EARTHCHARIOT       = new ShogiType("土車", "dosha",             "Earth chariot");
  static readonly YOUNGBIRD          = new ShogiType("𦬨鳥", "shakuchō",          "Young bird");
  static readonly VERMILLIONSPARROW  = new ShogiType("朱雀", "suzaku",            "Vermillion sparrow");
  static readonly DIVINESPARROW      = new ShogiType("神雀", "shinjaku",          "Divine sparrow");
  static readonly BLUEDRAGON         = new ShogiType("青龍", "seiryū",            "Blue dragon");
  static readonly DIVINEDRAGON       = new ShogiType("神龍", "shinryū",           "Divine dragon");
  static readonly ENCHANTEDBADGER    = new ShogiType("変狸", "henri",             "Enchanted badger");
  static readonly HORSEMAN           = new ShogiType("騎兵", "kihei",             "Horseman");
  static readonly SWOOPINGOWL        = new ShogiType("鴟行", "shigyō",            "Swooping owl");
  static readonly CLIMBINGMONKEY     = new ShogiType("登猿", "tōen",              "Climbing monkey");
  static readonly CATSWORD           = new ShogiType("猫刄", "myōjin",            "Cat sword");
  static readonly SWALLOWSWINGS      = new ShogiType("燕羽", "en'u",              "Swallow's wings");
  static readonly GLIDINGSWALLOW     = new ShogiType("燕行", "engyō",             "Gliding swallow");
  static readonly BLINDMONKEY        = new ShogiType("盲猿", "mōen",              "Blind monkey");
  static readonly FLYINGSTAG         = new ShogiType("飛鹿", "hiroku",            "Flying stag");
  static readonly BLINDTIGER         = new ShogiType("盲虎", "mōko",              "Blind tiger");
  static readonly OXCART             = new ShogiType("牛車", "gissha",            "Oxcart");
  static readonly PLODDINGOX         = new ShogiType("歬牛", "sengyū",            "Plodding ox");
  static readonly SIDEFLIER          = new ShogiType("横飛", "ōhi",               "Side flier");
  static readonly BLINDBEAR          = new ShogiType("盲熊", "mōyū",              "Blind bear");
  static readonly OLDRAT             = new ShogiType("老鼠", "rōso",              "Old rat");
  static readonly BIRDOFPARADISE     = new ShogiType("古寺", "jichō",             "Bird of paradise");
  static readonly SQUAREMOVER        = new ShogiType("方行", "hōgyō",             "Square mover");
  static readonly STRONGCHARIOT      = new ShogiType("強車", "kyōsha",            "Strong chariot");
  static readonly COILEDSERPENT      = new ShogiType("蟠蛇", "banja",             "Coiled serpent");
  static readonly COILEDDRAGON       = new ShogiType("蟠龍", "banryū",            "Coiled dragon");
  static readonly RECLININGDRAGON    = new ShogiType("臥龍", "garyū",             "Reclining dragon");
  static readonly FREEEAGLE          = new ShogiType("奔鷲", "honjū",             "Free eagle");
  static readonly LIONHAWK           = new ShogiType("獅鷹", "shiō",              "Lion hawk");
  static readonly CHARIOTSOLDIER     = new ShogiType("車兵", "shahei",            "Chariot soldier");
  static readonly HEAVENLYTETRARCHKING = new ShogiType("四天王","shitennō",       "Heavenly Tetrarch king");
  static readonly SIDESOLDIER        = new ShogiType("横兵", "ōhei",              "Side soldier");
  static readonly VERTICALSOLDIER    = new ShogiType("竪兵", "shuhei",            "Vertical soldier");
  static readonly WINDGENERAL        = new ShogiType("風将", "fūshō",             "Wind general");
  static readonly VIOLENTWIND        = new ShogiType("暴風", "bōfū",              "Violent wind");
  static readonly RIVERGENERAL       = new ShogiType("川将", "senshō",            "River general");
  static readonly CHINESERIVER       = new ShogiType("淮川", "waisen",            "Chinese river");
  static readonly MOUNTAINGENERAL    = new ShogiType("山将", "sanshō",            "Mountain general");
  static readonly PEACEFULMOUNTAIN   = new ShogiType("泰山", "taizan",            "Peaceful mountain");
  static readonly FRONTSTANDARD      = new ShogiType("前旗", "zenki",             "Front standard");
  static readonly HORSESOLDIER       = new ShogiType("馬兵", "bahei",             "Horse soldier");
  static readonly WOODGENERAL        = new ShogiType("木将", "mokushō",           "Wood general");
  static readonly OXSOLDIER          = new ShogiType("牛兵", "gyūhei",            "Ox soldier");
  static readonly RUNNINGOX          = new ShogiType("走牛", "sōgyū",             "Running ox");
  static readonly EARTHGENERAL       = new ShogiType("土将", "doshō",             "Earth general");
  static readonly BOARSOLDIER        = new ShogiType("猪兵", "chohei",            "Boar soldier");
  static readonly RUNNINGBOAR        = new ShogiType("走猪", "sōcho",             "Running boar");
  static readonly STONEGENERAL       = new ShogiType("石将", "sekishō",           "Stone general");
  static readonly LEOPARDSOLDIER     = new ShogiType("豹兵", "hyōhei",            "Leopard soldier");
  static readonly RUNNINGLEOPARD     = new ShogiType("走豹", "sōhyō",             "Running leopard");
  static readonly TILEGENERAL        = new ShogiType("瓦将", "gashō",             "Tile general");
  static readonly BEARSOLDIER        = new ShogiType("熊兵", "yūhei",             "Bear soldier");
  static readonly STRONGBEAR         = new ShogiType("強熊", "kyōyū",             "Strong bear");
  static readonly IRONGENERAL        = new ShogiType("鉄将", "tesshō",            "Iron general");
  static readonly GREATSTANDARD      = new ShogiType("大旗", "daiki",             "Great standard");
  static readonly GREATMASTER        = new ShogiType("大師", "daishi",            "Great master");
  static readonly RIGHTCHARIOT       = new ShogiType("右車", "usha",              "Right chariot");
  static readonly RIGHTIRONCHARIOT   = new ShogiType("右鉄車","utessha",          "Right iron chariot");
  static readonly LEFTCHARIOT        = new ShogiType("左車", "sasha",             "Left chariot");
  static readonly LEFTIRONCHARIOT    = new ShogiType("左鉄車","satessha",         "Left iron chariot");
  static readonly SIDEMONKEY         = new ShogiType("横猿", "ōen",               "Side monkey");
  static readonly VERTICALMOVER      = new ShogiType("竪行", "shugyō",            "Vertical mover");
  static readonly FLYINGOX           = new ShogiType("飛牛", "higyū",             "Flying ox");
  static readonly FIREOX             = new ShogiType("火牛", "kagyū",             "Fire ox");
  static readonly LONGBOWSOLDIER     = new ShogiType("弩兵", "dohei",             "Longbow soldier");
  static readonly LONGBOWGENERAL     = new ShogiType("弩将", "doshō",             "Longbow general");
  static readonly VERTICALPUP        = new ShogiType("竪狗", "shuku",             "Vertical pup");
  static readonly LEOPARDKING        = new ShogiType("豹王", "hyōō",              "Leopard king");
  static readonly VERTICALHORSE      = new ShogiType("竪馬", "shuba",             "Vertical horse");
  static readonly BURNINGSOLDIER     = new ShogiType("炮兵", "hōhei",             "Burning soldier");
  static readonly BURNINGGENERAL     = new ShogiType("炮将", "hōshō",             "Burning general");
  static readonly DRAGONHORSE        = new ShogiType("龍馬", "ryūme",             "Dragon horse");
  static readonly DRAGONKING         = new ShogiType("龍王", "ryūō",              "Dragon king");
  static readonly SWORDSOLDIER       = new ShogiType("刀兵", "tōhei",             "Sword soldier");
  static readonly SWORDGENERAL       = new ShogiType("刀将", "tōshō",             "Sword general");
  static readonly HORNEDFALCON       = new ShogiType("角鷹", "kakuō",             "Horned falcon");
  static readonly GREATFALCON        = new ShogiType("大鷹", "daiō",              "Great falcon");
  static readonly SOARINGEAGLE       = new ShogiType("飛鷲", "hijū",              "Soaring eagle");
  static readonly GREATEAGLE         = new ShogiType("大鷲", "daijū",             "Great eagle");
  static readonly SPEARSOLDIER       = new ShogiType("鎗兵", "sōhei",             "Spear soldier");
  static readonly SPEARGENERAL       = new ShogiType("鎗将", "sōshō",             "Spear general");
  static readonly VERTICALLEOPARD    = new ShogiType("竪豹", "shuhyō",            "Vertical leopard");
  static readonly GREATLEOPARD       = new ShogiType("大豹", "daihyō",            "Great leopard");
  static readonly SAVAGETIGER        = new ShogiType("猛虎", "mōko",              "Savage tiger");
  static readonly GREATTIGER         = new ShogiType("大虎", "daiko",             "Great tiger");
  static readonly CROSSBOWSOLDIER    = new ShogiType("弓兵", "kyūhei",            "Cross-bow soldier");
  static readonly CROSSBOWGENERAL    = new ShogiType("弓将", "kyūshō",            "Cross-bow general");
  static readonly ROARINGDOG         = new ShogiType("吼犬", "kōken",             "Roaring dog");
  static readonly LIONDOG            = new ShogiType("狛犬", "komainu",           "Lion dog");
  static readonly GREATELEPHANT      = new ShogiType("大象", "taizō",             "Great elephant");
  static readonly DOG                = new ShogiType("犬",   "inu",               "Dog");
  static readonly MULTIGENERAL       = new ShogiType("雜将", "suishō",            "Multi general");
  static readonly GOBETWEEN          = new ShogiType("仲人", "chūnin",            "Go between");
  static readonly PAWN               = new ShogiType("歩兵", "fuhyō",             "Pawn");
  static readonly EMPEROR            = new ShogiType("天王", "tennō",             "Emperor");
  static readonly DOVE               = new ShogiType("鳩槃", "kyūhan",            "Dove");
  static readonly POISONSNAKE        = new ShogiType("毒蛇", "dokuja",            "Poison snake");
  static readonly SIDECHARIOT        = new ShogiType("走車", "sōsha",             "Side chariot");
  static readonly SILVERHARE         = new ShogiType("銀兎", "ginto",             "Silver hare");
  static readonly SHEDEVIL           = new ShogiType("夜叉", "yasha",             "She devil");
  static readonly NEIGHBORKING       = new ShogiType("近王", "kinnō",             "Neighbor king");
  static readonly STANDARDBEARER     = new ShogiType("前旗", "zenki",             "Standard bearer");
  static readonly FREEEARTH          = new ShogiType("奔土", "hondo",             "Free earth");
  static readonly FREEGOER           = new ShogiType("奔人", "honnin",            "Free goer");
  static readonly FREESTONE          = new ShogiType("奔石", "honseki",           "Free stone");
  static readonly FREEIRON           = new ShogiType("奔鉄", "hontetsu",          "Free iron");
  static readonly FREETILE           = new ShogiType("奔瓦", "honga",             "Free tile");
  static readonly FREECOPPER         = new ShogiType("奔銅", "hondō",             "Free copper");
  static readonly FREESILVER         = new ShogiType("奔銀", "hongin",            "Free silver");
  static readonly FREEGOLD           = new ShogiType("奔金", "honkin",            "Free gold");
  static readonly FREECAT            = new ShogiType("奔猫", "honmyō",            "Free cat");
  static readonly BAT                = new ShogiType("蝙蝠", "kōmori",            "Bat");
  static readonly CHUNIN             = new ShogiType("中忍", "Chūnin",            "Chunin");
  static readonly TOKIN              = new ShogiType("と",   "Tokin",             "Tokin");
  static readonly OSHO               = new ShogiType("玉将", "Osho",              "King");
  static readonly SUIZO              = new ShogiType("酔象", "suizō",             "Drunken elephant");
  static readonly PHENIX             = new ShogiType("鳳凰", "Hoo",               "Phenix");
  static readonly CRANEKING          = new ShogiType("靏玉", "Kakugyoku",         "Crane King");
  static readonly TENACIOUSFALCON    = new ShogiType("力鷹", "Keiyo",             "Tenacious Falcon");
  static readonly SPARROWPAWN        = new ShogiType("萑歩", "Jakufu",            "Sparrow Pawn");
  static readonly RACINGCHARIOT      = new ShogiType("走車", "Sosha",             "Racing Chariot");
  static readonly ENCHANTEDFOX       = new ShogiType("走車", "Henko",             "Enchanted Fox");

  // -------------------------------------------------------------------------

  private readonly _kanji: string;
  private readonly _romaji: string;
  private readonly _englishName: string;

  // -------------------------------------------------------------------------

  private constructor(kanji: string, romaji: string, englishName: string) {
    this._kanji       = kanji;
    this._romaji      = romaji;
    this._englishName = englishName;
  }

  // -------------------------------------------------------------------------

  /** @java ShogiType#kanji() */
  kanji(): string {
    return this._kanji;
  }

  /** @java ShogiType#romaji() */
  romaji(): string {
    return this._romaji;
  }

  /** @java ShogiType#englishName() */
  englishName(): string {
    return this._englishName;
  }
}
