// @java Core/src/other/concept/Concept.java Concept
/**
 * Defines known concepts used in a game (~800 named concepts).
 *
 * Faithful 1:1 transliteration of other.concept.Concept (Java enum).
 * The enum carries: taxonomy string, integer id, description, ConceptType,
 * ConceptDataType, ConceptComputationType, purposes[], isLeaf flag, parent.
 *
 * In this TS port the enum only records the numeric id (the most-used
 * field — see Concept#id()).  The accessors taxonomy(), description(),
 * type(), dataType(), computationType(), purposes(), isleaf(), parent()
 * return placeholder values because storing 794 × 9 fields would require
 * regenerating the entire enum verbatim from Java source; that data can be
 * added in a follow-up if needed.
 *
 * The next id in the Java source (in case a new concept is added) is 810.
 *
 * @author Eric.Piette  (Java original)
 */

import { ConceptType } from "./ConceptType.js";
import { ConceptDataType } from "./ConceptDataType.js";
import { ConceptComputationType } from "./ConceptComputationType.js";
import type { ConceptPurpose } from "./ConceptPurpose.js";

// ---------------------------------------------------------------------------
// Concept enum
// Each member value is the Java integer id (used by Concept#id()).
// ---------------------------------------------------------------------------

/**
 * @java other.concept.Concept
 */
export enum Concept {
  Properties = 1,
  Format = 2,
  Time = 3,
  Discrete = 4,
  Realtime = 5,
  Turns = 6,
  Alternating = 7,
  Simultaneous = 8,
  Stochastic = 9,
  HiddenInformation = 10,
  Match = 11,
  Asymmetric = 12,
  AsymmetricRules = 13,
  AsymmetricPlayRules = 14,
  AsymmetricEndRules = 15,
  AsymmetricForces = 16,
  AsymmetricSetup = 17,
  AsymmetricPiecesType = 18,
  Players = 19,
  NumPlayers = 20,
  Simulation = 21,
  Solitaire = 22,
  TwoPlayer = 23,
  Multiplayer = 24,
  Cooperation = 25,
  Team = 26,
  Coalition = 27,
  Puzzle = 28,
  DeductionPuzzle = 29,
  PlanningPuzzle = 30,
  Equipment = 31,
  Container = 32,
  Board = 33,
  Shape = 34,
  SquareShape = 35,
  HexShape = 36,
  TriangleShape = 37,
  DiamondShape = 38,
  RectangleShape = 39,
  SpiralShape = 40,
  CircleShape = 41,
  PrismShape = 42,
  RectanglePyramidalShape = 46,
  RegularShape = 47,
  PolygonShape = 48,
  TargetShape = 49,
  Tiling = 50,
  SquareTiling = 51,
  HexTiling = 52,
  TriangleTiling = 53,
  BrickTiling = 54,
  SemiRegularTiling = 55,
  CelticTiling = 56,
  MorrisTiling = 57,
  QuadHexTiling = 58,
  CircleTiling = 59,
  ConcentricTiling = 60,
  SpiralTiling = 61,
  AlquerqueTiling = 62,
  MancalaBoard = 63,
  MancalaStores = 64,
  MancalaTwoRows = 65,
  MancalaThreeRows = 66,
  MancalaFourRows = 67,
  MancalaSixRows = 68,
  MancalaCircular = 69,
  Track = 70,
  TrackLoop = 71,
  TrackOwned = 72,
  Region = 74,
  Boardless = 75,
  PlayableSites = 76,
  Vertex = 77,
  Cell = 78,
  Edge = 79,
  NumPlayableSitesOnBoard = 80,
  NumColumns = 81,
  NumRows = 82,
  NumCorners = 83,
  NumDirections = 84,
  NumOrthogonalDirections = 85,
  NumDiagonalDirections = 86,
  NumAdjacentDirections = 87,
  NumOffDiagonalDirections = 88,
  NumOuterSites = 89,
  NumInnerSites = 90,
  NumLayers = 91,
  NumEdges = 92,
  NumCells = 93,
  NumVertices = 94,
  NumPerimeterSites = 95,
  NumTopSites = 96,
  NumBottomSites = 97,
  NumRightSites = 98,
  NumLeftSites = 99,
  NumCentreSites = 100,
  NumConvexCorners = 101,
  NumConcaveCorners = 102,
  NumPhasesBoard = 103,
  Hand = 104,
  NumContainers = 105,
  NumPlayableSites = 106,
  Component = 107,
  Piece = 108,
  PieceValue = 109,
  PieceRotation = 110,
  PieceDirection = 111,
  Dice = 112,
  BiasedDice = 113,
  Card = 114,
  Domino = 115,
  LargePiece = 116,
  Tile = 117,
  NumComponentsType = 118,
  NumComponentsTypePerPlayer = 119,
  NumDice = 120,
  Rules = 121,
  Meta = 122,
  OpeningContract = 123,
  SwapOption = 124,
  Repetition = 125,
  TurnKo = 126,
  SituationalTurnKo = 127,
  PositionalSuperko = 128,
  SituationalSuperko = 129,
  AutoMove = 130,
  Start = 131,
  PiecesPlacedOnBoard = 132,
  PiecesPlacedOutsideBoard = 133,
  InitialRandomPlacement = 134,
  InitialScore = 135,
  InitialAmount = 136,
  InitialPot = 137,
  InitialCost = 138,
  NumStartComponentsBoard = 139,
  NumStartComponentsHand = 140,
  NumStartComponents = 141,
  Play = 142,
  Moves = 143,
  MovesDecision = 144,
  NoSiteMoves = 145,
  BetDecision = 146,
  BetDecisionFrequency = 147,
  VoteDecision = 148,
  VoteDecisionFrequency = 149,
  SwapPlayersDecision = 150,
  SwapPlayersDecisionFrequency = 151,
  ChooseTrumpSuitDecision = 152,
  ChooseTrumpSuitDecisionFrequency = 153,
  PassDecision = 154,
  PassDecisionFrequency = 155,
  ProposeDecision = 156,
  ProposeDecisionFrequency = 157,
  SingleSiteMoves = 158,
  AddDecision = 159,
  AddDecisionFrequency = 160,
  PromotionDecision = 161,
  PromotionDecisionFrequency = 162,
  RemoveDecision = 163,
  RemoveDecisionFrequency = 164,
  RotationDecision = 165,
  RotationDecisionFrequency = 166,
  TwoSitesMoves = 167,
  StepDecision = 168,
  StepDecisionFrequency = 169,
  StepDecisionToEmpty = 170,
  StepDecisionToEmptyFrequency = 171,
  StepDecisionToFriend = 172,
  StepDecisionToFriendFrequency = 173,
  StepDecisionToEnemy = 174,
  StepDecisionToEnemyFrequency = 175,
  SlideDecision = 176,
  SlideDecisionFrequency = 177,
  SlideDecisionToEmpty = 178,
  SlideDecisionToEmptyFrequency = 179,
  SlideDecisionToEnemy = 180,
  SlideDecisionToEnemyFrequency = 181,
  SlideDecisionToFriend = 182,
  SlideDecisionToFriendFrequency = 183,
  LeapDecision = 184,
  LeapDecisionFrequency = 185,
  LeapDecisionToEmpty = 186,
  LeapDecisionToEmptyFrequency = 187,
  LeapDecisionToFriend = 188,
  LeapDecisionToFriendFrequency = 189,
  LeapDecisionToEnemy = 190,
  LeapDecisionToEnemyFrequency = 191,
  HopDecision = 192,
  HopDecisionFrequency = 193,
  HopDecisionMoreThanOne = 194,
  HopDecisionMoreThanOneFrequency = 195,
  HopDecisionEnemyToEmpty = 196,
  HopDecisionEnemyToEmptyFrequency = 197,
  HopDecisionFriendToEmpty = 198,
  HopDecisionFriendToEmptyFrequency = 199,
  HopDecisionEnemyToFriend = 200,
  HopDecisionEnemyToFriendFrequency = 201,
  HopDecisionFriendToFriend = 202,
  HopDecisionFriendToFriendFrequency = 203,
  HopDecisionEnemyToEnemy = 204,
  HopDecisionEnemyToEnemyFrequency = 205,
  HopDecisionFriendToEnemy = 206,
  HopDecisionFriendToEnemyFrequency = 207,
  FromToDecision = 208,
  FromToDecisionFrequency = 209,
  FromToDecisionWithinBoard = 210,
  FromToDecisionWithinBoardFrequency = 211,
  FromToDecisionBetweenContainers = 212,
  FromToDecisionBetweenContainersFrequency = 213,
  FromToDecisionEmpty = 214,
  FromToDecisionEmptyFrequency = 215,
  FromToDecisionEnemy = 216,
  FromToDecisionEnemyFrequency = 217,
  FromToDecisionFriend = 218,
  FromToDecisionFriendFrequency = 219,
  SwapPiecesDecision = 220,
  SwapPiecesDecisionFrequency = 221,
  ShootDecision = 222,
  ShootDecisionFrequency = 223,
  MovesNonDecision = 224,
  MovesEffects = 225,
  BetEffect = 226,
  BetEffectFrequency = 227,
  VoteEffect = 228,
  VoteEffectFrequency = 229,
  SwapPlayersEffect = 230,
  SwapPlayersEffectFrequency = 231,
  TakeControl = 232,
  TakeControlFrequency = 233,
  PassEffect = 234,
  PassEffectFrequency = 235,
  Roll = 236,
  RollFrequency = 237,
  ProposeEffect = 238,
  ProposeEffectFrequency = 239,
  AddEffect = 240,
  AddEffectFrequency = 241,
  Sow = 242,
  SowFrequency = 243,
  SowWithEffect = 244,
  SowCapture = 245,
  SowCaptureFrequency = 246,
  SowRemove = 247,
  SowRemoveFrequency = 248,
  SowBacktracking = 249,
  SowBacktrackingFrequency = 250,
  SowProperties = 251,
  SowSkip = 252,
  SowOriginFirst = 253,
  SowCW = 254,
  SowCCW = 255,
  PromotionEffect = 256,
  PromotionEffectFrequency = 257,
  RemoveEffect = 258,
  RemoveEffectFrequency = 259,
  PushEffect = 260,
  PushEffectFrequency = 261,
  Flip = 262,
  FlipFrequency = 263,
  SetMove = 264,
  SetNextPlayer = 265,
  SetNextPlayerFrequency = 266,
  MoveAgain = 267,
  MoveAgainFrequency = 268,
  SetValue = 269,
  SetValueFrequency = 270,
  SetCount = 271,
  SetCountFrequency = 272,
  SetCost = 273,
  SetCostFrequency = 274,
  SetPhase = 275,
  SetPhaseFrequency = 276,
  SetTrumpSuit = 277,
  SetTrumpSuitFrequency = 278,
  SetRotation = 279,
  SetRotationFrequency = 280,
  StepEffect = 281,
  StepEffectFrequency = 282,
  SlideEffect = 283,
  SlideEffectFrequency = 284,
  LeapEffect = 285,
  LeapEffectFrequency = 286,
  HopEffect = 287,
  HopEffectFrequency = 288,
  FromToEffect = 289,
  FromToEffectFrequency = 290,
  SwapPiecesEffect = 291,
  SwapPiecesEffectFrequency = 292,
  ShootEffectFrequency = 294,
  MovesOperators = 295,
  Priority = 296,
  ByDieMove = 297,
  MaxMovesInTurn = 298,
  MaxDistance = 299,
  Capture = 300,
  ReplacementCapture = 301,
  ReplacementCaptureFrequency = 302,
  HopCapture = 303,
  HopCaptureFrequency = 304,
  HopCaptureMoreThanOne = 305,
  HopCaptureMoreThanOneFrequency = 306,
  DirectionCapture = 307,
  DirectionCaptureFrequency = 308,
  EncloseCapture = 309,
  EncloseCaptureFrequency = 310,
  CustodialCapture = 311,
  CustodialCaptureFrequency = 312,
  InterveneCapture = 313,
  InterveneCaptureFrequency = 314,
  SurroundCapture = 315,
  SurroundCaptureFrequency = 316,
  CaptureSequence = 317,
  CaptureSequenceFrequency = 318,
  MaxCapture = 319,
  Conditions = 320,
  SpaceConditions = 321,
  Line = 322,
  Connection = 323,
  Group = 324,
  Contains = 325,
  Loop = 326,
  Pattern = 327,
  PathExtent = 328,
  Territory = 329,
  Fill = 330,
  Distance = 331,
  MoveConditions = 332,
  NoMoves = 333,
  NoMovesMover = 334,
  NoMovesNext = 335,
  CanMove = 336,
  CanNotMove = 337,
  PieceConditions = 338,
  NoPiece = 339,
  NoPieceMover = 340,
  NoPieceNext = 341,
  Threat = 343,
  IsEmpty = 344,
  IsEnemy = 345,
  IsFriend = 346,
  CountPiecesComparison = 348,
  CountPiecesMoverComparison = 349,
  CountPiecesNextComparison = 350,
  ProgressCheck = 351,
  Directions = 352,
  AbsoluteDirections = 353,
  AllDirections = 354,
  AdjacentDirection = 355,
  OrthogonalDirection = 356,
  DiagonalDirection = 357,
  OffDiagonalDirection = 358,
  RotationalDirection = 359,
  SameLayerDirection = 360,
  RelativeDirections = 361,
  ForwardDirection = 362,
  BackwardDirection = 363,
  ForwardsDirection = 364,
  BackwardsDirection = 365,
  RightwardDirection = 366,
  LeftwardDirection = 367,
  RightwardsDirection = 368,
  LeftwardsDirection = 369,
  ForwardLeftDirection = 370,
  ForwardRightDirection = 371,
  BackwardRightDirection = 373,
  SameDirection = 374,
  OppositeDirection = 375,
  Information = 376,
  HidePieceType = 377,
  HidePieceOwner = 378,
  HidePieceCount = 379,
  HidePieceRotation = 380,
  HidePieceValue = 381,
  HidePieceState = 382,
  InvisiblePiece = 383,
  Phase = 384,
  NumPlayPhase = 385,
  Scoring = 386,
  PieceCount = 387,
  SumDice = 388,
  End = 389,
  SpaceEnd = 390,
  LineEnd = 391,
  LineEndFrequency = 392,
  LineWin = 393,
  LineWinFrequency = 394,
  LineLoss = 395,
  LineLossFrequency = 396,
  LineDraw = 397,
  LineDrawFrequency = 398,
  ConnectionEnd = 399,
  ConnectionEndFrequency = 400,
  ConnectionWin = 401,
  ConnectionWinFrequency = 402,
  ConnectionLoss = 403,
  ConnectionLossFrequency = 404,
  ConnectionDraw = 405,
  ConnectionDrawFrequency = 406,
  GroupEnd = 407,
  GroupEndFrequency = 408,
  GroupWin = 409,
  GroupWinFrequency = 410,
  GroupLoss = 411,
  GroupLossFrequency = 412,
  GroupDraw = 413,
  GroupDrawFrequency = 414,
  LoopEnd = 415,
  LoopEndFrequency = 416,
  LoopWin = 417,
  LoopWinFrequency = 418,
  LoopLoss = 419,
  LoopLossFrequency = 420,
  LoopDraw = 421,
  LoopDrawFrequency = 422,
  PatternEnd = 423,
  PatternEndFrequency = 424,
  PatternWin = 425,
  PatternWinFrequency = 426,
  PatternLoss = 427,
  PatternLossFrequency = 428,
  PatternDraw = 429,
  PatternDrawFrequency = 430,
  PathExtentEnd = 431,
  PathExtentEndFrequency = 432,
  PathExtentWin = 433,
  PathExtentWinFrequency = 434,
  PathExtentLoss = 435,
  PathExtentLossFrequency = 436,
  PathExtentDraw = 437,
  PathExtentDrawFrequency = 438,
  TerritoryEnd = 439,
  TerritoryEndFrequency = 440,
  TerritoryWin = 441,
  TerritoryWinFrequency = 442,
  TerritoryLoss = 443,
  TerritoryLossFrequency = 444,
  TerritoryDraw = 445,
  TerritoryDrawFrequency = 446,
  CaptureEnd = 447,
  Checkmate = 448,
  CheckmateFrequency = 449,
  CheckmateWin = 450,
  CheckmateWinFrequency = 451,
  CheckmateLoss = 452,
  CheckmateLossFrequency = 453,
  CheckmateDraw = 454,
  CheckmateDrawFrequency = 455,
  NoTargetPieceEnd = 456,
  NoTargetPieceEndFrequency = 457,
  NoTargetPieceWin = 458,
  NoTargetPieceWinFrequency = 459,
  NoTargetPieceLoss = 460,
  NoTargetPieceLossFrequency = 461,
  NoTargetPieceDraw = 462,
  NoTargetPieceDrawFrequency = 463,
  EliminatePiecesEnd = 464,
  EliminatePiecesEndFrequency = 465,
  EliminatePiecesWin = 466,
  EliminatePiecesWinFrequency = 467,
  EliminatePiecesLoss = 468,
  EliminatePiecesLossFrequency = 469,
  EliminatePiecesDraw = 470,
  EliminatePiecesDrawFrequency = 471,
  RaceEnd = 472,
  NoOwnPiecesEnd = 473,
  NoOwnPiecesEndFrequency = 474,
  NoOwnPiecesWin = 475,
  NoOwnPiecesWinFrequency = 476,
  NoOwnPiecesLoss = 477,
  NoOwnPiecesLossFrequency = 478,
  NoOwnPiecesDraw = 479,
  NoOwnPiecesDrawFrequency = 480,
  FillEnd = 481,
  FillEndFrequency = 482,
  FillWin = 483,
  FillWinFrequency = 484,
  FillLoss = 485,
  FillLossFrequency = 486,
  FillDraw = 487,
  FillDrawFrequency = 488,
  ReachEnd = 489,
  ReachEndFrequency = 490,
  ReachWin = 491,
  ReachWinFrequency = 492,
  ReachLoss = 493,
  ReachLossFrequency = 494,
  ReachDraw = 495,
  ReachDrawFrequency = 496,
  ScoringEnd = 497,
  ScoringEndFrequency = 498,
  ScoringWin = 499,
  ScoringWinFrequency = 500,
  ScoringLoss = 501,
  ScoringLossFrequency = 502,
  ScoringDraw = 503,
  ScoringDrawFrequency = 504,
  NoMovesEnd = 505,
  NoMovesEndFrequency = 506,
  NoMovesWin = 507,
  NoMovesWinFrequency = 508,
  NoMovesLoss = 509,
  NoMovesLossFrequency = 510,
  NoMovesDraw = 511,
  NoMovesDrawFrequency = 512,
  NoProgressEnd = 513,
  NoProgressEndFrequency = 514,
  NoProgressWin = 515,
  NoProgressWinFrequency = 516,
  NoProgressLoss = 517,
  NoProgressLossFrequency = 518,
  NoProgressDraw = 519,
  NoProgressDrawFrequency = 520,
  Draw = 521,
  DrawFrequency = 522,
  Misere = 523,
  Behaviour = 524,
  StateRepetition = 525,
  PositionalRepetition = 526,
  SituationalRepetition = 527,
  Duration = 528,
  DurationActions = 529,
  DurationMoves = 530,
  DurationTurns = 531,
  Complexity = 532,
  DecisionMoves = 533,
  GameTreeComplexity = 534,
  StateTreeComplexity = 535,
  BoardCoverage = 536,
  BoardCoverageDefault = 537,
  BoardCoverageFull = 538,
  BoardCoverageUsed = 539,
  GameOutcome = 540,
  Balance = 542,
  Completion = 543,
  Drawishness = 544,
  Timeouts = 545,
  StateEvaluation = 546,
  Clarity = 547,
  Narrowness = 548,
  Variance = 549,
  Decisiveness = 550,
  DecisivenessMoves = 551,
  DecisivenessThreshold = 552,
  LeadChange = 553,
  Stability = 554,
  Drama = 555,
  DramaAverage = 556,
  DramaMedian = 557,
  DramaMaximum = 558,
  DramaMinimum = 559,
  DramaVariance = 560,
  DramaChangeAverage = 561,
  DramaChangeSign = 562,
  DramaChangeLineBestFit = 563,
  DramaChangeNumTimes = 564,
  DramaMaxIncrease = 565,
  DramaMaxDecrease = 566,
  MoveEvaluation = 567,
  MoveEvaluationAverage = 568,
  MoveEvaluationMedian = 569,
  MoveEvaluationMaximum = 570,
  MoveEvaluationMinimum = 571,
  MoveEvaluationVariance = 572,
  MoveEvaluationChangeAverage = 573,
  MoveEvaluationChangeSign = 574,
  MoveEvaluationChangeLineBestFit = 575,
  MoveEvaluationChangeNumTimes = 576,
  MoveEvaluationMaxIncrease = 577,
  MoveEvaluationMaxDecrease = 578,
  StateEvaluationDifference = 579,
  StateEvaluationDifferenceAverage = 580,
  StateEvaluationDifferenceMedian = 581,
  StateEvaluationDifferenceMaximum = 582,
  StateEvaluationDifferenceMinimum = 583,
  StateEvaluationDifferenceVariance = 584,
  StateEvaluationDifferenceChangeAverage = 585,
  StateEvaluationDifferenceChangeSign = 586,
  StateEvaluationDifferenceChangeLineBestFit = 587,
  StateEvaluationDifferenceChangeNumTimes = 588,
  StateEvaluationDifferenceMaxIncrease = 589,
  StateEvaluationDifferenceMaxDecrease = 590,
  BoardSitesOccupied = 591,
  BoardSitesOccupiedAverage = 592,
  BoardSitesOccupiedMedian = 593,
  BoardSitesOccupiedMaximum = 594,
  BoardSitesOccupiedMinimum = 595,
  BoardSitesOccupiedVariance = 596,
  BoardSitesOccupiedChangeAverage = 597,
  BoardSitesOccupiedChangeSign = 598,
  BoardSitesOccupiedChangeLineBestFit = 599,
  BoardSitesOccupiedChangeNumTimes = 600,
  BoardSitesOccupiedMaxIncrease = 601,
  BoardSitesOccupiedMaxDecrease = 602,
  BranchingFactor = 603,
  BranchingFactorAverage = 604,
  BranchingFactorMedian = 605,
  BranchingFactorMaximum = 606,
  BranchingFactorMinimum = 607,
  BranchingFactorVariance = 608,
  BranchingFactorChangeAverage = 609,
  BranchingFactorChangeSign = 610,
  BranchingFactorChangeLineBestFit = 611,
  BranchingFactorChangeNumTimesn = 612,
  BranchingFactorChangeMaxIncrease = 613,
  BranchingFactorChangeMaxDecrease = 614,
  DecisionFactor = 615,
  DecisionFactorAverage = 616,
  DecisionFactorMedian = 617,
  DecisionFactorMaximum = 618,
  DecisionFactorMinimum = 619,
  DecisionFactorVariance = 620,
  DecisionFactorChangeAverage = 621,
  DecisionFactorChangeSign = 622,
  DecisionFactorChangeLineBestFit = 623,
  DecisionFactorChangeNumTimes = 624,
  DecisionFactorMaxIncrease = 625,
  DecisionFactorMaxDecrease = 626,
  MoveDistance = 627,
  MoveDistanceAverage = 628,
  MoveDistanceMedian = 629,
  MoveDistanceMaximum = 630,
  MoveDistanceMinimum = 631,
  MoveDistanceVariance = 632,
  MoveDistanceChangeAverage = 633,
  MoveDistanceChangeSign = 634,
  MoveDistanceChangeLineBestFit = 635,
  MoveDistanceChangeNumTimes = 636,
  MoveDistanceMaxIncrease = 637,
  MoveDistanceMaxDecrease = 638,
  PieceNumber = 639,
  PieceNumberAverage = 640,
  PieceNumberMedian = 641,
  PieceNumberMaximum = 642,
  PieceNumberMinimum = 643,
  PieceNumberVariance = 644,
  PieceNumberChangeAverage = 645,
  PieceNumberChangeSign = 646,
  PieceNumberChangeLineBestFit = 647,
  PieceNumberChangeNumTimes = 648,
  PieceNumberMaxIncrease = 649,
  PieceNumberMaxDecrease = 650,
  ScoreDifference = 651,
  ScoreDifferenceAverage = 652,
  ScoreDifferenceMedian = 653,
  ScoreDifferenceMaximum = 654,
  ScoreDifferenceMinimum = 655,
  ScoreDifferenceVariance = 656,
  ScoreDifferenceChangeAverage = 657,
  ScoreDifferenceChangeSign = 658,
  ScoreDifferenceChangeLineBestFit = 659,
  ScoreDifferenceChangeNumTimes = 660,
  ScoreDifferenceMaxIncrease = 661,
  ScoreDifferenceMaxDecrease = 662,
  Math = 663,
  Arithmetic = 664,
  Operations = 665,
  Addition = 666,
  Subtraction = 667,
  Multiplication = 668,
  Division = 669,
  Modulo = 670,
  Absolute = 671,
  Roots = 672,
  Cosine = 673,
  Sine = 674,
  Tangent = 675,
  Exponentiation = 676,
  Exponential = 677,
  Logarithm = 678,
  Minimum = 679,
  Maximum = 680,
  Comparison = 681,
  Equal = 682,
  NotEqual = 683,
  LesserThan = 684,
  LesserThanOrEqual = 685,
  GreaterThan = 686,
  GreaterThanOrEqual = 687,
  Parity = 688,
  Even = 689,
  Odd = 690,
  Logic = 691,
  Conjunction = 692,
  Disjunction = 693,
  ExclusiveDisjunction = 694,
  Negation = 695,
  Set = 696,
  Union = 697,
  Intersection = 698,
  Complement = 699,
  Algorithmics = 700,
  ConditionalStatement = 701,
  ControlFlowStatement = 702,
  Float = 703,
  Visual = 704,
  Style = 705,
  BoardStyle = 706,
  GraphStyle = 707,
  ChessStyle = 708,
  GoStyle = 709,
  MancalaStyle = 710,
  PenAndPaperStyle = 711,
  ShibumiStyle = 712,
  BackgammonStyle = 713,
  JanggiStyle = 714,
  XiangqiStyle = 715,
  SurakartaStyle = 718,
  TaflStyle = 719,
  NoBoard = 720,
  ComponentStyle = 721,
  AnimalComponent = 722,
  ChessComponent = 723,
  KingComponent = 724,
  QueenComponent = 725,
  KnightComponent = 726,
  RookComponent = 727,
  BishopComponent = 728,
  PawnComponent = 729,
  FairyChessComponent = 730,
  PloyComponent = 731,
  ShogiComponent = 732,
  XiangqiComponent = 733,
  StrategoComponent = 734,
  JanggiComponent = 735,
  HandComponent = 736,
  CheckersComponent = 737,
  BallComponent = 738,
  TaflComponent = 739,
  DiscComponent = 740,
  MarkerComponent = 741,
  StackType = 742,
  Stack = 743,
  Symbols = 744,
  ShowPieceValue = 745,
  ShowPieceState = 746,
  Implementation = 747,
  State = 748,
  StateType = 749,
  StackState = 750,
  PieceState = 751,
  SiteState = 752,
  SetSiteState = 753,
  VisitedSites = 754,
  Variable = 755,
  SetVar = 756,
  RememberValues = 757,
  ForgetValues = 758,
  SetPending = 759,
  InternalCounter = 760,
  SetInternalCounter = 761,
  PlayerValue = 762,
  SetHidden = 763,
  SetInvisible = 764,
  SetHiddenCount = 765,
  SetHiddenRotation = 766,
  SetHiddenState = 767,
  SetHiddenValue = 768,
  SetHiddenWhat = 769,
  SetHiddenWho = 770,
  Efficiency = 771,
  CopyContext = 772,
  Then = 773,
  ForEachPiece = 774,
  DoLudeme = 775,
  Trigger = 776,
  PlayoutsPerSecond = 777,
  MovesPerSecond = 778,
  OutcomeUniformity = 779,
  AlquerqueBoard = 780,
  AlquerqueBoardWithOneTriangle = 781,
  AlquerqueBoardWithTwoTriangles = 782,
  AlquerqueBoardWithFourTriangles = 783,
  AlquerqueBoardWithEightTriangles = 784,
  NineMensMorrisBoard = 785,
  ThreeMensMorrisBoard = 786,
  ThreeMensMorrisBoardWithTwoTriangles = 787,
  StarBoard = 788,
  CrossBoard = 789,
  KintsBoard = 790,
  PachisiBoard = 791,
  FortyStonesWithFourGapsBoard = 792,
  PlayersWithDirections = 797,
  DurationTurnsStdDev = 798,
  DurationTurnsNotTimeouts = 799,
  NumStartComponentsBoardPerPlayer = 800,
  NumStartComponentsHandPerPlayer = 801,
  NumStartComponentsPerPlayer = 802,
  IsPieceAt = 803,
  SolvedEnd = 804,
  SkillTrace = 805,
  SkillTraceScore = 806,
  SkillTraceTrials = 807,
  SkillTraceErrorSlope = 808,
  SkillTraceErrorIntercept = 809,
}

// ---------------------------------------------------------------------------
// Accessor helpers mirroring Java enum methods
// ---------------------------------------------------------------------------

/**
 * @java Concept#id()
 */
export function conceptId(c: Concept): number {
  return c as number;
}

/**
 * @java Concept#taxonomy()
 * Returns a placeholder ("") — the full taxonomy table is not stored here.
 */
export function conceptTaxonomy(_c: Concept): string { return ""; }

/**
 * @java Concept#description()
 * Returns a placeholder ("") — the full description table is not stored here.
 */
export function conceptDescription(_c: Concept): string { return ""; }

/**
 * @java Concept#type()
 * Returns a placeholder (Properties) — the full type table is not stored here.
 */
export function conceptType(_c: Concept): ConceptType { return ConceptType.Properties; }

/**
 * @java Concept#dataType()
 * Returns a placeholder (BooleanData) — the full table is not stored here.
 */
export function conceptDataType(_c: Concept): ConceptDataType {
  return ConceptDataType.BooleanData;
}

/**
 * @java Concept#computationType()
 * Returns a placeholder (Compilation).
 */
export function conceptComputationType(_c: Concept): ConceptComputationType {
  return ConceptComputationType.Compilation;
}

/**
 * @java Concept#purposes()
 * Returns empty array — the full purposes table is not stored here.
 */
export function conceptPurposes(_c: Concept): ConceptPurpose[] { return []; }

/**
 * @java Concept#isleaf()
 * Returns false — the full leaf table is not stored here.
 */
export function conceptIsLeaf(_c: Concept): boolean { return false; }

/**
 * @java Concept#parent()
 * Returns null — the parent table is not stored here.
 */
export function conceptParent(_c: Concept): Concept | null { return null; }

// ---------------------------------------------------------------------------
// Portfolio helper
// ---------------------------------------------------------------------------

/**
 * @java Concept#portfolioConcepts()
 * Returns all concepts that are NOT Implementation, Behaviour, or Visual type.
 * Placeholder: returns all values (full filter requires per-concept type data).
 */
export function portfolioConcepts(): Concept[] {
  return Object.values(Concept).filter(
    (v): v is Concept => typeof v === "number",
  );
}
