#!/usr/bin/env python3
"""Extract Java enum constants for every enum class in ludeme-reflection.json.

The captured reflection metadata (ludeme-reflection.json) records enum classes
with only their synthetic (name, ordinal) constructor - not their constants -
so the ArgCompiler cannot validate that an ident like `P2` is a legal constant
of a given enum parameter the way Java's Enum.valueOf does during reflection
compilation. This script mirrors the constant lists straight from the Java
sources into src/ludii/compiler/gen/enum-constants.ts (same provenance pattern
as the reflection capture itself).

Usage: python3 tools/parity/extract-enum-constants.py
"""
import json, os, re

ENGINE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
JROOT = os.path.normpath(os.path.join(ENGINE, '../../../Core/src'))
REFL = os.path.join(ENGINE, 'tools/parity/ludeme-reflection.json')
OUT = os.path.join(ENGINE, 'src/ludii/compiler/gen/enum-constants.ts')

refl = json.load(open(REFL))
data = refl.get('classes', refl)
items = list(data.items()) if isinstance(data, dict) else [
    (c.get('name') or c.get('className'), c) for c in data]

def constants_of(src, simple_name):
    src = re.sub(r'/\*.*?\*/', '', src, flags=re.S)
    src = re.sub(r'//.*', '', src)
    m = re.search(r'\benum\s+' + re.escape(simple_name) + r'\b[^{]*\{', src)
    if not m:
        return None
    body = src[m.end():]
    # The constants section ends at the first ';' or '}' at brace-depth 0.
    # Split on depth-0 commas; each chunk's leading identifier is a constant
    # (constants may carry (args) and { class bodies } which sit at depth>0).
    consts, chunk, depth = [], '', 0
    for ch in body:
        if ch == '{' or ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
        elif ch == '}':
            if depth == 0:
                break
            depth -= 1
        if depth == 0 and ch in ',;':
            consts.append(chunk); chunk = ''
            if ch == ';':
                break
            continue
        chunk += ch
    consts.append(chunk)
    names = []
    for c in consts:
        m2 = re.match(r'\s*([A-Za-z_][A-Za-z0-9_]*)', c)
        if m2:
            names.append(m2.group(1))
    return names or None

out, missed = {}, []
for name, meta in items:
    if not meta or 'java.lang.Enum' not in (meta.get('assignableTo') or []):
        continue
    simple = name.split('.')[-1].split('$')[-1]
    path = os.path.join(JROOT, name.split('$')[0].replace('.', '/') + '.java')
    if not os.path.exists(path):
        missed.append(name); continue
    names = constants_of(open(path, encoding='utf-8', errors='replace').read(), simple)
    if names:
        out[name] = names
    else:
        missed.append(name)

with open(OUT, 'w') as f:
    f.write('// GENERATED by tools/parity/extract-enum-constants.py - DO NOT EDIT.\n')
    f.write('// Java enum constants per enum class in ludeme-reflection.json, mirrored from\n')
    f.write('// the Ludii Java sources so ArgCompiler.compileEnum can validate idents the way\n')
    f.write("// Java's Enum.valueOf does during reflection compilation.\n\n")
    f.write('export const ENUM_CONSTANTS: ReadonlyMap<string, ReadonlySet<string>> = new Map([\n')
    for k in sorted(out):
        f.write(f'  ["{k}", new Set({json.dumps(out[k])})],\n')
    f.write(']);\n')

print(f'wrote {len(out)} enums to {os.path.relpath(OUT, ENGINE)}; missed: {missed}')
