// @java Common/src/main/grammar/Report.java

/**
 * Report generated by expand/parse/compile process.
 *
 * @java main/grammar/Report.java
 * @author cambolbro
 */
export class Report {
  /** @java Report.errors */
  private readonly _errors: string[] = [];
  /** @java Report.warnings */
  private readonly _warnings: string[] = [];
  /** @java Report.notes */
  private readonly _notes: string[] = [];

  /** Ongoing report log to replace printlns to Console */
  private _log: string = "";

  /** @java Report.reportMessageFunctions */
  private _reportMessageFunctions: ReportMessenger | null = null;

  // -------------------------------------------------------------------------

  /** @java Report.errors() */
  public errors(): readonly string[] {
    return this._errors;
  }

  /** @java Report.warnings() */
  public warnings(): readonly string[] {
    return this._warnings;
  }

  /** @java Report.notes() */
  public notes(): readonly string[] {
    return this._notes;
  }

  // -------------------------------------------------------------------------
  // Error log

  /**
   * Clear the error log.
   *
   * @java Report.clearLog()
   */
  public clearLog(): void {
    this._log = "";
  }

  /**
   * Add a string to the error log.
   *
   * @java Report.addLog(String)
   */
  public addLog(str: string): void {
    this._log += str;
  }

  /**
   * Add a line to the error log.
   *
   * @java Report.addLogLine(String)
   */
  public addLogLine(str: string): void {
    this._log += str + "\n";
  }

  /**
   * @return Current error log as a string.
   *
   * @java Report.log()
   */
  public log(): string {
    return this._log;
  }

  // -------------------------------------------------------------------------

  /** @java Report.addError(String) */
  public addError(error: string): void {
    if (!this._errors.includes(error)) {
      this._errors.push(error);
    }
  }

  /** @java Report.addWarning(String) */
  public addWarning(warning: string): void {
    if (!this._warnings.includes(warning)) {
      this._warnings.push(warning);
    }
  }

  /** @java Report.addNote(String) */
  public addNote(note: string): void {
    if (!this._notes.includes(note)) {
      this._notes.push(note);
    }
  }

  // -------------------------------------------------------------------------

  /** @java Report.isError() */
  public isError(): boolean {
    return this._errors.length > 0;
  }

  /** @java Report.isWarning() */
  public isWarning(): boolean {
    return this._warnings.length > 0;
  }

  /** @java Report.isNote() */
  public isNote(): boolean {
    return this._notes.length > 0;
  }

  // -------------------------------------------------------------------------

  /** @java Report.clear() */
  public clear(): void {
    this._errors.length = 0;
    this._warnings.length = 0;
    this._notes.length = 0;
    this._log = "";
  }

  // -------------------------------------------------------------------------

  /**
   * @return Input string clipped to maximum char length.
   *
   * @java Report.clippedString(String, int)
   */
  public static clippedString(str: string, maxChars: number): string {
    if (str.length < maxChars) {
      return str;
    }
    return str.substring(0, maxChars - 3) + "...";
  }

  // -------------------------------------------------------------------------

  /** @java Report.toString() */
  public toString(): string {
    let sb = "";

    for (const error of this._errors) {
      sb += error;
    }

    for (const warning of this._warnings) {
      sb += "Warning: " + warning;
    }

    for (const note of this._notes) {
      sb += "Note: " + note;
    }

    return sb;
  }

  // -------------------------------------------------------------------------

  /** @java Report.getReportMessageFunctions() */
  public getReportMessageFunctions(): ReportMessenger | null {
    return this._reportMessageFunctions;
  }

  /** @java Report.setReportMessageFunctions(ReportMessenger) */
  public setReportMessageFunctions(reportMessageFunctions: ReportMessenger): void {
    this._reportMessageFunctions = reportMessageFunctions;
  }

  // -------------------------------------------------------------------------
}

// ---------------------------------------------------------------------------

/**
 * Report Messenger interface for printing report messages as needed.
 *
 * @java main/grammar/Report.ReportMessenger
 * @author Matthew.Stephenson
 */
export interface ReportMessenger {
  printMessageInStatusPanel(s: string): void;
  printMessageInAnalysisPanel(s: string): void;
}
