/* AUTO-GENERATED by scripts/build-builtin-defines.mjs — do not edit by hand. */

/**
 * Concatenated source of every `Common/res/def/**.def` file.
 * 164 built-in defines, 73615 bytes.
 */
export const BUILTIN_DEFINES_LUD = `// Common/res/def/conditions/IsInCheck.def
// Checks if a specific piece is threatened by any other enemy piece.
// #1 = The name of the piece (without the number).
// #2 = The roleType of the owner of the piece.
// #3 = The location where is the piece or The specific moves used to threat. This parameter is optional. If not specify the current location of the piece is used and all the legal moves are used.
// @example ("IsInCheck" "Osho" Next)
// @example ("IsInCheck" "King" Mover at:(to))

(define "IsInCheck"
    (is Threatened (id #1 #2) #3) 
)

// Common/res/def/conditions/player/IsEnemyAt.def
// Checks if an enemy is on a site. 
// #1 = The site.
// #2 = The level [the topest].
// @example ("IsEnemyAt" (to))

(define "IsEnemyAt"
    (is Enemy (who at:#1 #2))
)

// Common/res/def/conditions/player/IsFriendAt.def
// Checks if a friend is on a site. 
// #1 = The site.
// #2 = The level [the topest].
// @example ("IsFriendAt" (to))

(define "IsFriendAt"
    (is Friend (who at:#1 #2))
)

// Common/res/def/conditions/site/AllOwnedPiecesIn.def
// Checks if all pieces on the board owned by the mover are in a region.
// #1 = The region.
// @example ("AllOwnedPiecesIn" (sites Top))

(define "AllOwnedPiecesIn"
    (all Sites (sites Occupied by:Mover) if:(is In (site) #1))
)

// Common/res/def/conditions/site/DieNotUsed.def
// Checks if a die is not used when using the ludeme (forEach Die ...).
// @example ("DieNotUsed")

(define "DieNotUsed" (!= (pips) 0))

// Common/res/def/conditions/site/HandEmpty.def
// Checks if all the sites in a specific hand are empty. This ludemeplex is working only for non stacking games.
// #1 = The owner of the hand, can be a RoleType or the index of the owner.
// @example ("HandEmpty" Mover)

(define "HandEmpty"
    (all Sites (sites Hand #1) if:(= 0 (count Cell at:(site))))
)

// Common/res/def/conditions/site/HandOccupied.def
// Checks if at least a site in a specific hand is not empty. This ludemeplex is working only for non stacking games.
// #1 = The owner of the hand, can be a RoleType or the index of the owner.
// @example ("HandOccupied" Mover)

(define "HandOccupied"
    (not (all Sites (sites Hand #1) if:(= 0 (count Cell at:(site)))))
)

// Common/res/def/conditions/site/HasFreedom.def
// Checks if a group of pieces has some liberties around it. The specified directions (by default Adjacent) are the directions between the elements of the group.
// #1 = = Directions of the pieces in the group.
// @example ("HasFreedom" Orthogonal)

(define "HasFreedom" (> (count Liberties #1) 0))

// Common/res/def/conditions/site/IsEmptyAndNotVisited.def
// Checks if a site is empty and not visited so far in the same turn.
// #1 = The site.
// @example ("IsEmptyAndNotVisited" (to))

(define "IsEmptyAndNotVisited"
    (and 
        (is Empty #1) 
        (not (is Visited #1)) 
    )
)

// Common/res/def/conditions/site/IsPhaseOne.def
// Checks if a site is phase 1.
// #1 = The site.
// @example ("IsPhaseOne" (between))

(define "IsPhaseOne"
    (= 1 (phase of:#1))
)

// Common/res/def/conditions/site/IsPhaseZero.def
// Checks if a site is phase 0.
// #1 = The site.
// @example ("IsPhaseZero" (between))

(define "IsPhaseZero"
    (= 0 (phase of:#1))
)

// Common/res/def/conditions/site/IsPieceAt.def
// Checks if a piece #1 owned by #2 is at a site #3.
// #1 = The name of the piece.
// #2 = The owner of the piece.
// #3 = The site.
// #4 = The level.
// @example ("IsPieceAt" "Ball" Shared 32)

(define "IsPieceAt"
    (= (what at:#3 #4) (id #1 #2))
)

// Common/res/def/conditions/site/IsSingleGroup.def
// Checks if only one single group with pieces owned by a player exists.
//#1 = The owner of the pieces in the group.
//#2 = The direction used to connect the pieces in the group (by default Adjacent).
//@example ("IsSingleGroup" Mover)

(define "IsSingleGroup"
    (= 1 (count Groups #2 if:(= (who at:(to)) #1)))
)

// Common/res/def/conditions/site/NoPieceOnBoard.def
// Checks if the board is empty. This ludemeplex is not working for games involving stacks.
// @example ("NoPieceOnBoard)

(define "NoPieceOnBoard" (all Sites (sites Board) if:(= 0 (count at:(site)))))

// Common/res/def/conditions/site/NoSites.def
// Checks if a region has no sites.
// #1 = The region.
// @example ("NoSites" (sites Empty))

(define "NoSites"
    (= (count Sites in:#1) 0)
)

// Common/res/def/conditions/stack/IsEmptyOrSingletonStack.def
// Checks if a stack has a size of 1 at a site or if the site is empty.
// #1 = The site.
// @example ("IsEmptyOrSingletonStack" (to))

(define "IsEmptyOrSingletonStack" (= (topLevel at:#1) 0))

// Common/res/def/conditions/stack/IsSingletonStack.def
// Checks if a stack has a size of 1 at a site.
// #1 = The site.
// @example ("IsSingletonStack" (to))

(define "IsSingletonStack" (= 1 (size Stack at:#1)))

// Common/res/def/conditions/stack/IsTopLevel.def
// Checks if a level is at the top of a stack.
// #1 = The site.
// @example ("IsTopLevel" (to))

(define "IsTopLevel" (= (topLevel at:#1) (level)))

// Common/res/def/conditions/stack/NoEnemyOrOnlyOne.def
// Checks if no enemy or only one in a stack game.
// #1 = The site.
// @example ("NoEnemyOrOnlyOne" (to))

(define "NoEnemyOrOnlyOne" 
    (or (not ("IsEnemyAt" #1))
        ("IsSingletonStack" #1)
    )		
)

// Common/res/def/conditions/track/IsEndTrack.def
// Checks if a site returned by a track is the ending site of the track. 
// #1 = The site.
// @example ("IsEndTrack" ("NextSiteOnTrack" 3))

(define "IsEndTrack"
    (= #1 End)
)

// Common/res/def/conditions/track/IsNotEndTrack.def
// Checks if a site returned by a track is not the ending site of the track. 
// #1 = The site.
// @example ("IsNotEndTrack" ("NextSiteOnTrack" 3))

(define "IsNotEndTrack"
    (!= #1 End)
)

// Common/res/def/conditions/track/IsNotOffBoard.def
// Checks if a site returned by a track is not off board. 
// #1 = The site.
// @example ("IsNotOffBoard" ("NextSiteOnTrack" 3))

(define "IsNotOffBoard"
    (!= #1 Off)
)

// Common/res/def/conditions/track/IsOffBoard.def
// Checks if a site returned by a track is off board. 
// #1 = The site.
// @example ("IsOffBoard" ("NextSiteOnTrack" 3))

(define "IsOffBoard"
    (= #1 Off)
)

// Common/res/def/conditions/turn/NewTurn.def
// Checks if this is new turn, i.e. the current move is not the previous mover.
// @example ("NewTurn")

(define "NewTurn"
    (not (is Prev Mover))
)

// Common/res/def/conditions/turn/SameTurn.def
// Checks if the previous mover is the same player than the current mover, consequently this is the same turn.
// @example ("SameTurn")

(define "SameTurn"
    (is Prev Mover)
)

// Common/res/def/directions/LastDirection.def
// Returns the direction between the last \`from' location and the last \`to' location.
// #1 = The site type of the sites.
// @example ("LastDirection" Cell)

(define "LastDirection" 
    (directions #1 from:(last From) to:(last To))
)

// Common/res/def/equipment/DraughtsEquipment.def
// Defines all the equipment used in most of the draught games.
// #1 = The graph of the board.
// #2 = The default site type to use [Optional by default Cell].
// #3 = An optional element of the equipment.
// @example ("DraughtsEquipment" (square 8))

(define "DraughtsEquipment"
    (equipment { 
        (board #1 #2) 
        (piece "Counter" P1 N)
        (piece "Counter" P2 S) 
        (piece "DoubleCounter" Each)
        (regions P1 (sites Bottom))
        (regions P2 (sites Top))
        #3
    })
)

// Common/res/def/equipment/board/CrossBoard.def
// Defines a regular start board (example: Kaooa).
// #1 = The dimension of the start.
// @example ("StarBoard" 5)

(define "StarBoard"
    (board 
        (splitCrossings (regular Star #1))
        use:Vertex
    )
)

// Common/res/def/equipment/board/LascaBoard.def
// Defines the original Lasca board.
// @example ("LascaBoard")

(define "LascaBoard"
    (board 
        ("LascaGraph")
        use:Vertex
    )
)

// Common/res/def/equipment/board/StarBoard.def
// Defines a regular cross board tilled by squares (example: Pachisi).
// #1 = The dimension of an arm of the cross.
// #2 = The full dimension of the board.
// #3 = The default site type of the board.
// #4 = The type of the diagonals of each tiling.
// @example ("CrossBoard" 3 7 use:Vertex diagonals:Alternating)

(define "CrossBoard"
    (board 
        ("CrossGraph" #1 #2 #4)
        #3
    )
)

// Common/res/def/equipment/board/alquerque/AlquerqueBoard.def
// Defines a rectangular board with Alquerque-style alternating diagonals.
// @example ("AlquerqueBoard" 5 5)

(define "AlquerqueBoard"
    (board 
        ("AlquerqueGraph" #1 #2)
        use:Vertex
    )
)

// Common/res/def/equipment/board/alquerque/AlquerqueBoardWithBottomAndTopTriangles.def
// Defines a rectangular board with Alquerque-style alternating diagonals with a triangle extension at the bottom and another at the top.
// @example ("AlquerqueBoardWithBottomAndTopTriangles")

(define "AlquerqueBoardWithBottomAndTopTriangles"
    (board
        ("AlquerqueGraphWithBottomAndTopTriangles")
        use:Vertex
    )
)

// Common/res/def/equipment/board/alquerque/AlquerqueBoardWithBottomTriangle.def
// Defines a rectangular board with Alquerque-style alternating diagonals with a triangle extension at the bottom.
// @example ("AlquerqueBoardWithBottomTriangle")

(define "AlquerqueBoardWithBottomTriangle"
    (board 
        ("AlquerqueGraphWithBottomTriangle") 
        use:Vertex
    ) 
)

// Common/res/def/equipment/board/alquerque/AlquerqueBoardWithEightTriangles.def
// Defines a rectangular board with Alquerque-style alternating diagonals with eight triangle extensions.
// @example ("AlquerqueBoardWithEightTriangles")

(define "AlquerqueBoardWithEightTriangles"
    (board 
        (merge { 
            (shift 2 2 (square 5 diagonals:Alternating)) 
            (shift 2 0 (wedge 3)) 
            (shift 5 3 (rotate 90 (wedge 3))) 
            (shift 2 6 (rotate 180 (wedge 3))) 
            (shift -1 3 (rotate 270 (wedge 3))) 
            (shift 0.65 1.15 (scale 0.5 (rotate -45 (wedge 3))))
            (shift 5.35 1.15 (scale 0.5 (rotate 45 (wedge 3))))
            (shift 5.35 5.85 (scale 0.5 (rotate 135 (wedge 3))))
            (shift 0.65 5.85 (scale 0.5 (rotate -135 (wedge 3))))
        }) 
        use:Vertex
    )
)

// Common/res/def/equipment/board/alquerque/AlquerqueBoardWithFourTriangles.def
// Defines a rectangular board with Alquerque-style alternating diagonals with four triangle extensions on each side.
// @example ("AlquerqueBoardWithFourTriangles")

(define "AlquerqueBoardWithFourTriangles"
    (board 
        ("AlquerqueGraphWithFourTriangles") 
        use:Vertex
    ) 
)

// Common/res/def/equipment/board/morris/NineMensMorrisBoard.def
// Defines a nine men's morris board.
// @example ("NineMensMorrisBoard")

(define "NineMensMorrisBoard"
    (board (concentric Square rings:3) use:Vertex) 
)

// Common/res/def/equipment/board/morris/ThreeMensMorrisBoard.def
// Defines a Three Men's Morris board.
// @example ("ThreeMensMorrisBoard")

(define "ThreeMensMorrisBoard"
    (board 
        ("AlquerqueGraph" 3 3)
        use:Vertex
    )
)

// Common/res/def/equipment/board/morris/ThreeMensMorrisBoardWithLeftAndRightTriangles.def
// Defines a Three Men's Morris board with two triangle extensions at the left and right.
// @example ("ThreeMensMorrisBoardWithLeftAndRightTriangles")

(define "ThreeMensMorrisBoardWithLeftAndRightTriangles"
    (board 
        ("ThreeMensMorrisGraphWithLeftAndRightTriangles")
        use:Vertex
    )
)

// Common/res/def/equipment/board/race/BackgammonBoard.def
// Defines a backgammon board (without the style).
// #1 = The tracks of the players.
// @example ("BackgammonBoard")

(define "BackgammonBoard"
    (board (rectangle 2 13) 
        #1 
        use:Vertex
    ) 
)

// Common/res/def/equipment/board/race/FortyStonesWithFourGapsBoard.def
// Defines a circle board defined with 40 stones, with a gap after each 10 stones. The board is playable on the edges.
// @example ("FortyStonesWithFourGapsBoard")

(define "FortyStonesWithFourGapsBoard"
    (board
        (add
            (remove 
                (concentric {44})
                vertices:{43 21 0 22}
            )
            edges:{{20 18} {0 1} {19 21} {38 39}}
        )
        #1
        use:Edge
    )
)

// Common/res/def/equipment/board/race/KintsBoard.def
// Defines a rectangular board with some arcs used in some native american games such as Kints.
// #1 = The tracks of the players.
// @example ("KintsBoard")

(define "KintsBoard"
    (board
        (add
            (merge { 
                (shift -1.25 -0.34 (rotate 30 (rectangle 6 1)))
                (rectangle 1 5)
                (rectangle 5 1)
                (shift 0 6 (rectangle 5 1))
                (shift 0 10 (rectangle 1 5))
                (shift 7 0 (rectangle 1 5))
                (shift 7 10 (rectangle 1 5))
                (shift 11 0 (rectangle 5 1))
                (shift 11 6 (rectangle 5 1))
                (shift 12.25 5.33 (rotate 30 (rectangle 6 1)))
            })
            edges:{{13 14} {22 28} {37 36} {9 23}}
        )
        #1
        use:Vertex
    )
)

// Common/res/def/equipment/board/race/PachisiBoard.def
// Defines a pachisi board.
// @example ("PachisiBoard")

(define "PachisiBoard"
    (board 
        (add
            (hole
                ("CrossGraph" 3 19)
                (poly {{8 8} {8 11} {11 11} {11 8}})
            )
            cells:{ { 8 28 48 68 69 70 71 51 31 11 10 9 } }
        )
        #1
    )
)

// Common/res/def/equipment/board/race/TableBoard.def
// Defines a table board (without the style).
// #1 = The tracks of the players.
// @example ("TableBoard")

(define "TableBoard"
    (board 
        (merge {
            (rectangle 1 6) 
            (shift 7 0 (rectangle 1 6))
            (shift 0 6 (rectangle 1 6))
            (shift 7 6 (rectangle 1 6))
        })
        #1
        use:Vertex
    )
)

// Common/res/def/equipment/board/tracks/backgammon/BackgammonTracks.def
// Defines the most popular backgammon tracks.
// #1 = An optional End site.
// @example ("BackgammonTracks")

(define "BackgammonTracks"
    {
    (track "Track1" {12..7 5..0 13..18 20..25 #1} P1 directed:True)
    (track "Track2" {25..20 18..13 0..5 7..12 #1} P2 directed:True)
    } 
)

// Common/res/def/equipment/board/tracks/backgammon/BackgammonTracksSameDirectionOppositeCorners.def
// Defines backgammon tracks following the same direction for each player but starting from opposite corners.
// #1 = An optional End site.
// @example ("BackgammonTracksSameDirectionOppositeCorners")

(define "BackgammonTracksSameDirectionOppositeCorners"
    {
    (track "Track1" {0..5 7..12 25..20 18..13 #1} P1 directed:True)
    (track "Track2" {25..20 18..13 0..5 7..12 #1} P2 directed:True)
    } 
)

// Common/res/def/equipment/board/tracks/backgammon/BackgammonTracksSameDirectionOppositeCornersWithBars.def
// Defines backgammon tracks following the same direction for each player but starting from opposite corners in using the bar of the board.
// #1 = An optional End site.
// @example ("BackgammonTracksSameDirectionOppositeCornersWithBars")

(define "BackgammonTracksSameDirectionOppositeCornersWithBars"
    {
    (track "Track1" {6 13..18 20..25 12..7 5..0} P1 directed:True)
    (track "Track2" {19 12..7 5..0 13..18 20..25} P2 directed:True)
    } 
)

// Common/res/def/equipment/board/tracks/backgammon/BackgammonTracksSameDirectionOppositeCornersWithBars2.def
// Defines backgammon tracks following the same direction for each player but starting from opposite corners in using the bar of the board.
// #1 = An optional End site.
// @example ("BackgammonTracksSameDirectionOppositeCornersWithBars2")

(define "BackgammonTracksSameDirectionOppositeCornersWithBars2"
    {
    (track "Track1" {6 25..20 18..13 0..5 7..12 #1} P1 directed:True)
    (track "Track2" {19 0..5 7..12 25..20 18..13 #1} P2 directed:True)
    } 
)

// Common/res/def/equipment/board/tracks/backgammon/BackgammonTracksSameDirectionWithBar.def
// Defines backgammon tracks following the same direction for each player in using the bar of the board.
// #1 = An optional End site.
// @example ("BackgammonTracksSameDirectionWithBar")

(define "BackgammonTracksSameDirectionWithBar"
    {
    (track "Track1" {6 0..5 7..12 25..20 18..13 #1} P1 directed:True)
    (track "Track2" {19 0..5 7..12 25..20 18..13 #1} P2 directed:True)
    } 
)

// Common/res/def/equipment/board/tracks/backgammon/BackgammonTracksSameDirectionWithHands.def
// Defines backgammon tracks following the same direction for each player in using the hands of the players.
// #1 = An optional End site.
// @example ("BackgammonTracksSameDirectionWithHands")

(define "BackgammonTracksSameDirectionWithHands"
    {
    (track "Track1" {26 25..20 18..13 0..5 7..12 #1} P1 directed:True)
    (track "Track2" {27 25..20 18..13 0..5 7..12 #1} P2 directed:True)
    } 
)

// Common/res/def/equipment/board/tracks/backgammon/BackgammonTracksWithBar.def
// Defines the most popular backgammon tracks in using the bar of the board.
// #1 = An optional End site.
// @example ("BackgammonTracksWithBar")

(define "BackgammonTracksWithBar"
    {
    (track "Track1" {6 12..7 5..0 13..18 20..25 #1} P1 directed:True)
    (track "Track2" {19 25..20 18..13 0..5 7..12 #1} P2 directed:True)
    } 
)

// Common/res/def/equipment/board/tracks/backgammon/BackgammonTracksWithHands.def
// Defines the most popular backgammon tracks in using the hands of the players.
// #1 = An optional End site.
// @example ("BackgammonTracksWithHands")

(define "BackgammonTracksWithHands"
    {
    (track "Track1" {26 12..7 5..0 13..18 20..25 #1} P1 directed:True)
    (track "Track2" {27 25..20 18..13 0..5 7..12 #1} P2 directed:True)
    } 
)

// Common/res/def/equipment/board/tracks/table/TableTracksOpposite.def
// Defines two opposite table tracks.
// #1 = An optional End site.
// @example ("TableTracksOpposite")

(define "TableTracksOpposite"
    {
    (track "Track1" {0..11 23..12 #1} P1 directed:True)
    (track "Track2" {12..23 11..0 #1} P2 directed:True)
    }
)

// Common/res/def/equipment/board/tracks/table/TableTracksOpposite2.def
// Defines two opposite table tracks.
// #1 = An optional End site.
// @example ("TableTracksOpposite2")

(define "TableTracksOpposite2"
    {
    (track "Track1" {11..0 12..23 #1} P1 directed:True)
    (track "Track2" {23..12 0..11 #1} P2 directed:True)
    }
)

// Common/res/def/equipment/board/tracks/table/TableTracksOppositeWithHands.def
// Defines two opposite table tracks and using hand sites.
// #1 = An optional End site.
// @example ("TableTracksOppositeWithHands")

(define "TableTracksOppositeWithHands"
    {
    (track "Track1" {24 0..11 23..12 #1} P1 directed:True)
    (track "Track2" {25 12..23 11..0 #1} P2 directed:True)
    }
)

// Common/res/def/equipment/board/tracks/table/TableTracksOppositeWithHands2.def
// Defines two opposite table tracks and using hand sites.
// #1 = An optional End site.
// @example ("TableTracksOppositeWithHands2")

(define "TableTracksOppositeWithHands2"
    {
    (track "Track1" {24 11..0 12..23 #1} P1 directed:True)
    (track "Track2" {25 23..12 0..11 #1} P2 directed:True)
    }
)

// Common/res/def/equipment/board/tracks/table/TableTracksSameDirectionOppositeCorners.def
// Defines table tracks following the same direction for each player but starting from opposite corners.
// #1 = An optional End site.
// @example ("TableTracksSameDirectionOppositeCorners")

(define "TableTracksSameDirectionOppositeCorners"
    {
    (track "Track1" {11..0 12..23 #1} P1 directed:True)
    (track "Track2" {12..23 11..0 #1} P2 directed:True)
    }
)

// Common/res/def/equipment/board/tracks/table/TableTracksSameDirectionWithHands.def
// Defines two table tracks following the same directions and using hand sites.
// #1 = An optional End site.
// @example ("TableTracksSameDirectionWithHands")

(define "TableTracksSameDirectionWithHands"
    {
    (track "Track1" {24 0..5 6..11 23..18 17..12 #1} P1 directed:True)
    (track "Track2" {25 0..5 6..11 23..18 17..12 #1} P2 directed:True)
    }
)

// Common/res/def/equipment/dice/StickDice.def
// Defines a specified number of D2 dice with values 0 and 1.
// @example ("StickDice" 4)

(define "StickDice"
    (dice d:2 from:0 num:#1)
)

// Common/res/def/equipment/graph/CrossGraph.def
// Defines a regular cross graph tilled by squares (example: Pachisi).
// #1 = The dimension of an arm of the cross.
// #2 = The full dimension of the board.
// #3 = The type of the diagonals of each tiling.
// @example ("CrossGraph" 3 7 diagonals:Alternating)

(define "CrossGraph"
    (merge 
        (shift 0 (/ (- #2 #1) 2) (rectangle #1 #2 #3))
        (shift (/ (- #2 #1) 2) 0 (rectangle #2 #1 #3)) 
    )
)

// Common/res/def/equipment/graph/LascaGraph.def
// Defines the original Lasca graph.
// @example ("LascaGraph")

(define "LascaGraph"
    (graph
        vertices:{ {0 0} {2 0} {4 0} {6 0} {1 1} {3 1} {5 1} {0 2} {2 2} {4 2} 
        {6 2} {1 3} {3 3} {5 3} {0 4} {2 4} {4 4} {6 4} {1 5} {3 5} 
        {5 5} {0 6} {2 6} {4 6} {6 6}
        }
        edges:{ {0 4} {1 4} {1 5} {2 5} {2 6} {3 6} {4 7} {4 8} {5 8} {5 9}
        {6 9} {6 10} {7 11} {8 11} {8 12} {9 12} {9 13} {10 13} {11 14}
        {11 15} {12 15} {12 16} {13 16} {13 17} {14 18} {15 18} {15 19}
        {16 19} {16 20} {17 20} {18 21} {18 22} {19 22} {19 23} {20 23}
        {20 24} 
        }
    )
)

// Common/res/def/equipment/graph/alquerque/AlquerqueGraph.def
// Defines a rectangular graph with Alquerque-style alternating diagonals.
// @example ("AlquerqueGraph" 5 5)

(define "AlquerqueGraph"
    (rectangle #1 #2 diagonals:Alternating)
)

// Common/res/def/equipment/graph/alquerque/AlquerqueGraphWithBottomAndTopTriangles.def
// Defines a rectangular graph with Alquerque-style alternating diagonals with a triangle extension at the bottom and another at the top.
// @example ("AlquerqueGraphWithBottomAndTopTriangles")

(define "AlquerqueGraphWithBottomAndTopTriangles"
    (merge {
        (square 5 diagonals:Alternating)
        (shift 0 4 (rotate 180 (wedge 3)))
        (shift 0 -2 (wedge 3))
    })
)

// Common/res/def/equipment/graph/alquerque/AlquerqueGraphWithBottomTriangle.def
// Defines a rectangular graph with Alquerque-style alternating diagonals with a triangle extension at the bottom.
// @example ("AlquerqueGraphWithBottomTriangle")

(define "AlquerqueGraphWithBottomTriangle"
    (merge 
        (shift 0 2 (square 5 diagonals:Alternating)) 
        (wedge 3)
    ) 
)

// Common/res/def/equipment/graph/alquerque/AlquerqueGraphWithFourTriangles.def
// Defines a rectangular graph with Alquerque-style alternating diagonals with four triangle extension on each side.
// @example ("AlquerqueGraphWithFourTriangles")

(define "AlquerqueGraphWithFourTriangles"
    (merge { 
        (shift 2 2 (square 5 diagonals:Alternating)) 
        (shift 2 0 (wedge 3)) 
        (shift 5 3 (rotate 90 (wedge 3))) 
        (shift 2 6 (rotate 180 (wedge 3))) 
        (shift -1 3 (rotate 270 (wedge 3))) 
    }) 
)

// Common/res/def/equipment/graph/morris/ThreeMensMorrisGraphWithLeftAndRightTriangles.def
// Defines a Three Men's Morris graph with two triangle extensions at the left and right.
// @example ("ThreeMensMorrisGraphWithLeftAndRightTriangles")

(define "ThreeMensMorrisGraphWithLeftAndRightTriangles"
    (merge {
        (rectangle 3 3 diagonals:Alternating)
        (shift 1.5 0.5 (rotate -90 (wedge 2))) 
        (shift -1.5 0.5 (rotate 90 (wedge 2))) 
    })
)

// Common/res/def/equipment/pieces/ChessBishop.def
// Defines a piece moving like a bishop in Chess.
// #1 = The name of the piece.
// #2 = Consequences of the capture effect.
// #3 = The consequences of the moves.
// @example ("ChessBishop" "Bishop")

(define "ChessBishop"
    (piece #1 Each 
        (move
            Slide
            Diagonal
            (to 
                if:("IsEnemyAt" (to))  
                (apply 
                    (remove 
                        (to) 
                        #2
                    )
                ) 
            )
            #3
        ) 		
    )
)

// Common/res/def/equipment/pieces/ChessKing.def
// Defines a piece moving like a king in Chess (castling is not described in this ludemeplex).
// #1 = The name of the piece.
// #2 = Consequences of the capture effect.
// #3 = The consequences of the moves.
// @example ("ChessKing" "King")

(define "ChessKing"
    (piece #1 Each 
        (move
            Step 
            (to 
                if:(not ("IsFriendAt" (to))) 
                (apply 
                    (if ("IsEnemyAt" (to)) 
                        (remove 
                            (to) 
                            #2
                        )
                    )
                ) 
            ) 
            #3
        )
    )
)

// Common/res/def/equipment/pieces/ChessKnight.def
// Defines a piece moving like a knight in Chess.
// #1 = The name of the piece.
// #2 = Consequences of the capture effect.
// #3 = The consequences.
// @example ("ChessKnight" "Knight")

(define "ChessKnight"
    (piece #1 Each ("LeapCapture" "KnightWalk" #2 #3))
)

// Common/res/def/equipment/pieces/ChessPawn.def
// Defines a piece moving like a pawn in Chess (En Passant, Initial double step moves and promotion are not described in this ludemeplex).
// #1 = The name of the piece.
// #2 = Other moves which can be added to the pawn pieces.
// #3 = The consequences.
// @example ("ChessPawn" "Pawn")

(define "ChessPawn"
    (piece #1 Each 
        (or {
            "StepForwardToEmpty" 
            ("StepToEnemy" (directions {FR FL}))
            #2
            }
            #3
        )
    )
)

// Common/res/def/equipment/pieces/ChessQueen.def
// Defines a piece moving like a queen in Chess.
// #1 = The name of the piece.
// #2 = Consequences of the capture effect.
// #3 = The consequences of the moves.
// @example ("ChessQueen" "Queen")

(define "ChessQueen"
    (piece #1 Each 
        (move
            Slide
            (to 
                if:("IsEnemyAt" (to))  
                (apply 
                    (remove 
                        (to) 
                        #2
                    )
                ) 
            )
            #3
        ) 		
    )
)

// Common/res/def/equipment/pieces/ChessRook.def
// Defines a piece moving like a rook in Chess.
// #1 = The name of the piece.
// #2 = Consequences of the capture effect.
// #3 = The consequences of the moves.
// @example ("ChessRook" "Rook")

(define "ChessRook" 
    (piece #1 Each 
        (move
            Slide
            Orthogonal
            (to 
                if:("IsEnemyAt" (to))  
                (apply 
                    (remove 
                        (to) 
                        #2
                    )
                ) 
            )
            #3
        ) 		
    )
)

// Common/res/def/equipment/pieces/ShogiGold.def
// Defines a piece moving like a gold in Shogi. The effect of the capture have to be defined.
// #1 = The name of the piece.
// #2 = The capture effect.
// #3 = The consequences of the moves.
// @example ("ShogiGold" "Tokin")

(define "ShogiGold"
    (piece #1 Each 
        (move Step 
            (directions {Forward Backward Rightward Leftward FL FR})
            (to if:(not ("IsFriendAt" (to))) 
                #2
            ) 
            #3 
        ) 	
    )
)

// Common/res/def/equipment/players/TwoPlayersNorthSouth.def
// Defines two players, P1 moving in direction to the north and P2 moving in direction to the south.
// @example ("TwoPlayersNorthSouth")

(define "TwoPlayersNorthSouth"
    (players {(player N) (player S)})
)

// Common/res/def/functions/LastDistance.def
// Returns the number of steps between the last \`from' location and the last \`to' location.
// #1 = The relation type to use between the sites [Adjacent].
// @example ("LastDistance")

(define "LastDistance" 
    (count Steps #1 (last From) (last To))
)

// Common/res/def/functions/NextSiteOnTrack.def
// Returns the next site on a track.
// #1 = The number of steps.
// #2 = From site [(from)].
// #3 = Which track [First track of the mover].
// @example ("NextSiteOnTrack" 3)

(define "NextSiteOnTrack"
    (trackSite Move #2 #3 steps:#1)
)

// Common/res/def/functions/OccupiedNbors.def
// Returns the number of pieces owned by a player around a given site.
// #1 = The site to test around.
// #2 = The owner of the pieces to count.
// @example ("OccupiedNbors" (to) Mover)

(define "OccupiedNbors"
    (count Sites 
        in:(intersection 
            (sites Around #1) 
            (sites Occupied by:#2)  
        )
    )
)

// Common/res/def/functions/mancala/LastHoleSowed.def
// Returns a region of one site corresponding to the last \`to' position after applying the consequences. In the mancala games, this site is the last hole in which a seed was sowed. 
// @example ("LastHoleSowed")

(define "LastHoleSowed" (sites {(last To afterConsequence:True)}))

// Common/res/def/functions/mancala/OppositeOuterPit.def
// Returns the index of the outer opposite pit on a mancala board with four rows. This ludemeplex is working only if the description is defining "Columns" as the number of holes of the board.
// #1 = The site.
// @example ("OppositeOuterPit" (to))

(define "OppositeOuterPit" (if (is Mover P1) (+ #1 (* "Columns" 2)) (- #1 (* "Columns" 2))))

// Common/res/def/functions/mancala/OppositePit.def
// Returns the index of the opposite pit on a mancala board. This ludemeplex is working only if the description is defining "Columns" as the number of holes of the board.
// #1 = The site.
// @example ("OppositePit" (to))

(define "OppositePit" (if (is Mover P1) (+ #1 "Columns") (- #1 "Columns")))

// Common/res/def/functions/mancala/OppositePitTwoRows.def
// Returns the index of the opposite pit on a two rows mancala board. This ludemeplex is working only if the description is defining "Columns" as the number of holes of the board.
// #1 = The site.
// @example ("OppositePitTwoRows" (to))

(define "OppositePitTwoRows" (if (is In #1 (sites Bottom)) (+ #1 "Columns") (- #1 "Columns")))

// Common/res/def/rules/end/CaptureAll.def
// Checks if a player has no piece and lose. This ludemeplex can be used only in an ending condition.
// @example ("CaptureAll" Next)

(define "CaptureAll"
    (if (no Pieces #1) (result #1 Loss))
)

// Common/res/def/rules/end/CaptureAllTeam.def
// Checks if all the enemies have no piece and makes the current team to win. This ludemeplex can be used only in an ending condition.
// @example ("CaptureAllTeam")

(define "CaptureAllTeam"
    (if (no Pieces Enemy) (result TeamMover Win))
)

// Common/res/def/rules/end/Checkmate.def
// If the next player is checkmate, the mover is winning. This ludemeplex can be used only in an ending condition.
// #1 = The name of the piece to check.
// @example ("Checkmate" "King")

(define "Checkmate"
    (if (and 
            ("IsInCheck" #1 Next)
            (not (can Move (do (forEach Piece Next) ifAfterwards:(not ("IsInCheck" #1 Next)))))
        ) 
        (result Mover Win)
    )
)

// Common/res/def/rules/end/HavingLessPiecesLoss.def
// Checks if a player has a less or equal number of pieces and lose. This ludemeplex can be used only in an ending condition.
// @example ("HavingLessPiecesLoss" Next 2)

(define "HavingLessPiecesLoss"
    (if (<= (count Pieces #1) #2) (result #1 Loss))
)

// Common/res/def/rules/end/MancalaByScoreWhen.def
// Ends a mancala game when a condition is verified in computing the score of each player thanks to a ludemeplex called "PiecesOwnedBy" taking in input the role of P1 or P2. This ludemeplex can be used only in an ending condition.
// #1 The condition.
// @example ("MancalaByScoreWhen" (no Moves Next))

(define "MancalaByScoreWhen"
    (if #1 
        (byScore {
            (score P1 ("PiecesOwnedBy" P1)) 
            (score P2 ("PiecesOwnedBy" P2))
        })
    )
)

// Common/res/def/rules/end/hunt/NoMovesLossAndLessNumPiecesPlayerLoss.def
// Checks if the next player has no legal moves and the next player loses and checks if a specific player has less or equal than a number of pieces to lose. This ludemeplex can be used only in an ending condition.
// #1 = The owner of the pieces.
// #2 = The number of pieces.
// @example ("NoMovesLossAndLessNumPiecesPlayerLoss" P1 3)

(define "NoMovesLossAndLessNumPiecesPlayerLoss"
    {
    ("NoMoves" Loss)
    (if (<= (count Pieces #1) #2) (result #1 Loss))
    }
)

// Common/res/def/rules/end/hunt/NoMovesLossAndNoPiecesPlayerLoss.def
// Checks if the next player has no legal moves and the next player loses and checks if a specific player has no pieces to lose. This ludemeplex can be used only in an ending condition.
// #1 = The owner of the pieces.
// @example ("NoMovesLossAndNoPiecesPlayerLoss" P1)

(define "NoMovesLossAndNoPiecesPlayerLoss"
    {
    ("NoMoves" Loss)
    (if (no Pieces #1) (result #1 Win))
    }
)

// Common/res/def/rules/end/hunt/NoMovesP1NoPiecesP2.def
// Checks if P1 has no moves and P2 wins and checks if P2 has no pieces and P1 wins. This ludemeplex can be used only in an ending condition.
// @example ("NoMovesP1NoPiecesP2")

(define "NoMovesP1NoPiecesP2"
    {
    (if (no Moves P1) (result P2 Win))
    (if (no Pieces P2) (result P1 Win))
    }
)

// Common/res/def/rules/end/hunt/NoMovesP2NoPiecesP1.def
// Checks if P2 has no moves and P1 wins and checks if P1 has no pieces and P2 wins. This ludemeplex can be used only in an ending condition.
// @example ("NoMovesP2NoPiecesP1")

(define "NoMovesP2NoPiecesP1"
    {
    (if (no Moves P2) (result P1 Win))
    (if (no Pieces P1) (result P2 Win))
    }
)

// Common/res/def/rules/end/race/EscapeTeamWin.def
// Checks if the team has no pieces and makes it win. This ludemeplex can be used only in an ending condition.
// @example ("EscapeTeamWin")

(define "EscapeTeamWin"
    (if (no Pieces TeamMover) (result TeamMover Win))
)

// Common/res/def/rules/end/race/EscapeWin.def
// Checks if the mover has no pieces and makes it win. This ludemeplex can be used only in an ending condition.
// @example ("EscapeWin")

(define "EscapeWin"
    (if (no Pieces Mover) (result Mover Win))
)

// Common/res/def/rules/end/race/FillWin.def
// If the mover is filling all the spaces of a region with his pieces, the mover is winning. This ludemeplex can be used only in an ending condition.
// #1 = The name of the piece to check.
// @example ("FillWin" (sites Top))

(define "FillWin"
    (if 
        (= (sites Occupied by:Mover) #1)
        (result Mover Win)
    )
)

// Common/res/def/rules/end/race/PieceTypeReachWin.def
// Checks if a specific piece type reached a region and makes a player is wining. This ludemeplex can be used only in an ending condition.
// #1 = The name of the piece.
// #2 = The region to reach.
// #3 = The player
// @example ("PieceTypeReachWin" "Jarl2" (sites Corners) P2)

(define "PieceTypeReachWin"
    (if (is Within (id #1) in:#2) (result #3 Win))
)

// Common/res/def/rules/end/race/ReachWin.def
// If the mover is reaching a space of a region with his last movement, a player is winning. This ludemeplex can be used only in an ending condition.
// #1 = The region to reach.
// #2 = The player to win.
// @example ("ReachWin" (sites Top) P1)

(define "ReachWin"
    (if
        (is In (last To) #1)
        (result #2 Win)
    )
)

// Common/res/def/rules/end/space/BlockWin.def
// If the next player has no legal moves, the mover is winning. This ludemeplex can be used only in an ending condition.
// @example ("BlockWin")

(define "BlockWin"
    (if (no Moves Next) (result Mover Win))
)

// Common/res/def/rules/end/space/DrawIfNoMoves.def
// Checks if a player has no legal moves and the game ends in a draw.
// #1 = The Player with no moves.
// @example ("DrawIfNoMoves" Next)

(define "DrawIfNoMoves"
    (if (no Moves #1) (result Mover Draw))
)

// Common/res/def/rules/end/space/ForEachNonMoverNoMovesLoss.def
// Makes a player losing when this player has no moves. This ludemeplex can be used only in an ending condition.
// @example ("ForEachNonMoverNoMovesLoss")

(define "ForEachNonMoverNoMovesLoss"
    (forEach NonMover
        if:(no Moves Player)
        (result Player Loss)
    )
)

// Common/res/def/rules/end/space/ForEachPlayerNoMovesLoss.def
// Makes a player losing when this player has no moves. This ludemeplex can be used only in an ending condition.
// @example ("ForEachPlayerNoMovesLoss")

(define "ForEachPlayerNoMovesLoss"
    (forEach Player
        if:(no Moves Player)
        (result Player Loss)
    )
)

// Common/res/def/rules/end/space/ForEachPlayerNoPiecesLoss.def
// Makes a player losing when this player has no pieces. This ludemeplex can be used only in an ending condition.
// @example ("ForEachPlayerNoPiecesLoss")

(define "ForEachPlayerNoPiecesLoss"
    (forEach Player
        if:(no Pieces Player)
        (result Player Loss)
    )
)

// Common/res/def/rules/end/space/Line3Win.def
// If the mover has 3 pieces aligned, the mover is winning. This ludemeplex can be used only in an ending condition.
// #1 = Directions of the line (by default Adjacent) or role type of the owner of the pieces making the line.
// @example ("Line3Win")

(define "Line3Win"
    (if (is Line 3 #1) (result Mover Win))
)

// Common/res/def/rules/end/space/MisereBlockWin.def
// If the mover has no legal moves, the mover is winning. This ludemeplex can be used only in an ending condition.
// @example ("MisereBlockWin")

(define "MisereBlockWin"
    (if (no Moves Mover) (result Mover Win))
)

// Common/res/def/rules/end/space/NoMoves.def
// Checks if the next player has no legal moves and apply a specific result to the next player. This ludemeplex can be used only in an ending condition.
// #1 = The result to apply.
// @example ("NoMoves" Loss)

(define "NoMoves"
    (if (no Moves Next) (result Next #1))
)

// Common/res/def/rules/end/space/SingleGroupWin.def
// Checks if only one single group with pieces owned by a player exists. This ludemeplex can be used only in an ending condition.
// #1 = The owner of the pieces in the group.
// #2 = The direction used to connect the pieces in the group (by default Adjacent).
// @example ("SingleGroupWin" Mover)

(define "SingleGroupWin"
    (if ("IsSingleGroup" #1 #2) (result #1 Win))
)

// Common/res/def/rules/phase/PhaseMovePiece.def
// Defines a phase to move each piece according to the move ludeme associated with each piece.
// #1 = The name of the phase.
// #2 = Optional ending condition applied only in this phase.
// @example ("PhaseMovePiece" "Movement")

(define "PhaseMovePiece"
    (phase #1 (play (forEach Piece)) #2)
)

// Common/res/def/rules/play/capture/CustodialCapture.def
// Defines a custodial capture in all the directions specified (by default Adjacent) to capture an enemy piece. The enemy piece is removed.
// #1 = Directions of the capture.
// #2 = Constraints related to the number of pieces to capture.
// #3 = The consequences.
// @example ("CustodialCapture")

(define "CustodialCapture"
    (custodial 
        (from (last To))
        #1
        (between  
            #2
            if:("IsEnemyAt" (between))
            (apply (remove (between)))
        )
        (to if:("IsFriendAt" (to)))
        #3
    )
)

// Common/res/def/rules/play/capture/CustodialCapturePieceType.def
// Defines a custodial capture in all the directions specified (by default Adjacent) to capture a specific piece type owned by the next player. The piece is removed.
// #1 = The name of the piece type.
// #2 = Directions of the capture.
// #3 = Constraints related to the number of pieces to capture.
// #4 = The consequences.
// @example ("CustodialCapturePieceType" "Jarl")

(define "CustodialCapturePieceType"
    (custodial 
        (from (last To))
        #2
        (between 
            #3
            if:("IsPieceAt" #1 Next (between))
            (apply (remove (between)))
        )
        (to if:("IsFriendAt" (to)))
        #4
    )
)

// Common/res/def/rules/play/capture/EncloseCapture.def
// Defines an enclose capture by all the directions specified (by default Adjacent). The enemy pieces are removed.
// #1 = Directions of the capture.
// #2 = The consequences.
// @example ("EncloseCapture")

(define "EncloseCapture"
    (enclose 
        (from (last To)) 
        #1 
        (between 
            if:("IsEnemyAt" (between)) 
            (apply (remove (between))) 
        )
        #2
    )
)

// Common/res/def/rules/play/capture/HittingCapture.def
// Defines the capture of an enemy piece returning to a site. This ludemeplex can be used only as an effect.
// @example ("HittingCapture" (handSite (who at:(to))))

(define "HittingCapture"
    (apply 
        if:("IsEnemyAt" (to)) 
        (fromTo (from (to)) (to #1))
    ) 
)

// Common/res/def/rules/play/capture/HittingStackCapture.def
// Defines the capture of a stack with an enemy piece at the top returning to a site. This ludemeplex can be used only as an effect.
// @example ("HittingStackCapture" (handSite (who at:(to) level:(level))))

(define "HittingStackCapture"
    (apply
        (if ("IsEnemyAt" (to))
            (forEach Level (to) FromTop
                (fromTo
                    (from (to) level:(level))
                    (to #1)
                )
            )
        )
    )
)

// Common/res/def/rules/play/capture/InterveneCapture.def
// Defines an intervene capture in all the directions specified (by default Adjacent). The enemy piece is removed.
// #1 = Directions of the capture.
// #2 = The consequences.
// @example ("InterveneCapture")

(define "InterveneCapture"
    (intervene 
        (from (last To))
        #1
        (to 
            if:("IsEnemyAt" (to))
            (apply (remove (to)))
        )
        #2
    )
)

// Common/res/def/rules/play/capture/SurroundCapture.def
// Defines a surround capture in all the directions specified (by default Adjacent). The enemy piece is removed.
// #1 = Directions of the capture.
// #2 = Constraints related to the number of pieces to capture.
// #3 = The consequences.
// @example ("SurroundCapture")

(define "SurroundCapture"
    (surround 
        (from (last To)) 
        #1
        (between 
            #2
            if:("IsEnemyAt" (between)) 
            (apply (remove (between)))
        ) 
        (to 
            if:("IsFriendAt" (to))
        )
        #3
    )
)

// Common/res/def/rules/play/consequences/ReplayIfCanMove.def
// Move again if the player can do the move specified.
// #1 = The moves.
// #2 = The movement to allow if the piece did not reach the region (Optional).
// @example ("ReplayIfCanMove" (forEach Piece))

(define "ReplayIfCanMove"
    (if (can Move #1) (moveAgain) #2) 
)

// Common/res/def/rules/play/consequences/ReplayIfLine3.def
// Move again if the last \`to' position just made a line of 3.
// #1 = The directions of the line (by default adjacent).
// #1 = If true, then lines cannot exceed minimum length (by default false).
// @example ("ReplayIfLine3")

(define "ReplayIfLine3"
    (if (is Line 3 #1 #2) 
        (moveAgain)
    )
)

// Common/res/def/rules/play/consequences/ReplayInMovingOn.def
// Move again if the last \`to' position is on a specified region.
// #1 = The region.
// @example ("ReplayInMovingOn" (sites Top))

(define "ReplayInMovingOn"
    (if (is In (last To) #1) 
        (moveAgain) 
    ) 
)

// Common/res/def/rules/play/consequences/ReplayNotAllDiceUsed.def
// Move again if all the dice are not used when using the ludeme (forEach Die ...).
// @example ("ReplayNotAllDiceUsed")

(define "ReplayNotAllDiceUsed"
    (if (not (all DiceUsed))
        (moveAgain)
    )
)

// Common/res/def/rules/play/dice/RollEachNewTurnMove.def
// Roll dice at each new turn before to compute the legal moves.
// #1 = The legal moves.
// #2 = The consequences.
// @example ("RollEachNewTurnMove" (forEach Piece))

(define "RollEachNewTurnMove"
    (do (if ("NewTurn") (roll))
        next:#1
        #2
    )
)

// Common/res/def/rules/play/dice/RollMove.def
// Roll dice before to compute the legal moves.
// #1 = The legal moves.
// #2 = The consequences.
// @example ("RollMove" (forEach Piece))

(define "RollMove"
    (do (roll) 
        next:#1
        #2
    )
)

// Common/res/def/rules/play/moves/MoveToEmptyOrOccupiedByLargerPiece.def
// Defines a move from a region to any empty sites or sites occupied by a larger pieces on the board. This ludemeplex involves stacks and the size of the piece are related to the indexes of the pieces (in the hypothesis that each player has the same number of pieces). Some graphic metadata will be needed to scale the pieces according to this.
// #1 = The from region.
// #2 = A condition on the from location (optional).
// @example ("MoveToEmptyOrOccupiedByLargerPiece" (sites Hand Mover))

(define "MoveToEmptyOrOccupiedByLargerPiece"
    (move 
        (from #1)
        (to 
            (sites Board)
            if:(and 
                (!= (from) (to)) 
                (or (is Empty (to)) 
                    (< 
                        (- (what at:(from) level:(topLevel at:(from))) (who at:(from) level:(topLevel at:(from)))) 
                        (- (what at:(to) level:(topLevel at:(to))) (who at:(to) level:(topLevel at:(to)))) 
                    )
                )
            )
        )
    )
)

// Common/res/def/rules/play/moves/hop/HopAllPiecesToEmpty.def
// Defines a hop move in all the directions specified (by default Adjacent) over any occupied site to an empty site.
// #1 = The from site.
// #2 = Directions of the hop.
// #3 = The range of the hop.
// #4 = The consequences.
// @example ("HopAllPiecesToEmpty")

(define "HopAllPiecesToEmpty"
    (move Hop 
        #1
        #2
        (between #3 if:(is Occupied (between))) 
        (to if:(is Empty (to))) 
        #4
    )
)

// Common/res/def/rules/play/moves/hop/HopCapture.def
// Defines a hop move in all the directions specified (by default Adjacent) over an enemy to an empty site. The enemy piece is removed.
// #1 = The from site.
// #2 = Directions of the hop.
// #3 = The consequences.
// @example ("HopCapture")

(define "HopCapture"
    (move Hop
        #1
        #2
        (between
            if:("IsEnemyAt" (between))
            (apply (remove (between)))
        )
        (to if:(is Empty (to)))
        #3
    )
)

// Common/res/def/rules/play/moves/hop/HopCaptureDistance.def
// Defines a hop move in all the directions specified (by default Adjacent) over an enemy to an empty site at any distance. The enemy piece is removed.
// #1 = The from site.
// #2 = Directions of the hop.
// #3 = The range of pieces you can hop (by default 1).
// #4 = The consequences.
// @example ("HopCaptureDistance" (from (last To)) Diagonal)

(define "HopCaptureDistance"
    (move Hop
        #1
        #2
        (between
            before:(count Rows) 
            #3
            after:(count Rows)
            if:("IsEnemyAt" (between))
            (apply (remove (between)))
        )
        (to if:(is Empty (to)))
        #4
    )
)

// Common/res/def/rules/play/moves/hop/HopCaptureDistanceNotAlreadyHopped.def
// Defines a hop move in the specified directions over an enemy to an empty site at any distance. The enemy pieces are removed and you can not hop a piece you already hopped during your turn.
// #1 = The from site.
// #2 = The directions.
// #2 = The consequences.
// @example ("HopCaptureDistanceNotAlreadyHopped")

(define "HopCaptureDistanceNotAlreadyHopped"
    (move Hop 
        #1 
        #2 
        (between 
            before:(count Rows) 
            after:(count Rows)
            if:(and 
                (not (is In (between) (sites ToClear))) 
                ("IsEnemyAt" (between))
            )
            (apply (remove (between)))
        ) 
        (to if:(is Empty (to))) 
        #3
    )
)

// Common/res/def/rules/play/moves/hop/HopDiagonalCapture.def
// Defines a hop move in all the diagonal directions over an enemy to an empty site. The enemy piece is removed.
// @example ("HopDiagonalCapture")

(define "HopDiagonalCapture" 
    (move Hop 
        Diagonal
        (between 
            if:("IsEnemyAt" (between)) 
            (apply (remove (between)))
        )
        (to if:(is Empty (to)))
    )
)

// Common/res/def/rules/play/moves/hop/HopDiagonalSequenceCapture.def
// Defines a sequence of hop move in all the diagonal directions over an enemy to an empty site. 
// The enemy pieces are removed.
// #1 = Maximum distance before the hop [0].
// #2 = Maximum distance after the hop [0].
// #3 = When to perform the capture (immediately or at the end of the turn) [immediately].
// @example ("HopDiagonalSequenceCapture")
// @example ("HopDiagonalSequenceCapture" before:(count Rows) after:(count Rows) at:EndOfTurn)

(define "HopDiagonalSequenceCapture" 
    (move Hop
        Diagonal
        (between 
            #1
            #2
            if:("IsEnemyAt" (between)) 
            (apply (remove (between) #3))
        )
        (to if:(is Empty (to)))
        (then 
            (if (can Move 
                    (hop 
                        (from (last To)) 
                        Diagonal
                        (between 
                            #1
                            #2
                            if:(and 
                                (not (is In (between) (sites ToClear))) 
                                ("IsEnemyAt" (between))
                            )
                        )
                        (to if:(is Empty (to)))
                    )
                ) 
                (moveAgain)
            )
        )
    )
)

// Common/res/def/rules/play/moves/hop/HopDiagonalSequenceCaptureAgain.def
// Defines a sequence of hop move in all the diagonal directions over an enemy to an empty site from the last \`\`to'' location of the previous move. 
// The enemy pieces are removed.
// #1 = Maximum distance before the hop [0].
// #2 = Maximum distance after the hop [0].
// #3 = When to perform the capture (immediately or at the end of the turn) [immediately].
// @example ("HopDiagonalSequenceCaptureAgain")
// @example ("HopDiagonalSequenceCaptureAgain" before:(count Rows) after:(count Rows) at:EndOfTurn)

(define "HopDiagonalSequenceCaptureAgain" 
    (move Hop
        (from (last To)) 
        Diagonal
        (between 
            #1
            #2
            if:(and (not (is In (between) (sites ToClear))) ("IsEnemyAt" (between))) 
            (apply (remove (between) #3))
        )
        (to if:(is Empty (to)))
        (then 
            (if (can Move 
                    (hop 
                        (from (last To))
                        Diagonal 
                        (between
                            #1
                            #2
                            if:(and 
                                (not (is In (between) (sites ToClear))) 
                                ("IsEnemyAt" (between))
                            )
                        )
                        (to if:(is Empty (to)))
                    )
                ) 
                (moveAgain)
            )
        )
    )
)

// Common/res/def/rules/play/moves/hop/HopFriendCapture.def
// Defines a hop move in all the directions specified (by default Adjacent) over a friend to an empty site. The friend piece is removed.
// #1 = The from site.
// #2 = Directions of the hop.
// #3 = The consequences.
// @example ("HopFriendCapture")

(define "HopFriendCapture"
    (move Hop
        #1
        #2
        (between
            if:("IsFriendAt" (between))
            (apply (remove (between)))
        )
        (to if:(is Empty (to)))
        #3
    )
)

// Common/res/def/rules/play/moves/hop/HopInternationalDraughtsStyle.def
// Defines a hop move in diagonal over an enemy to an empty site. The enemy pieces are removed at the end of the turn and you can not hop a piece you already hopped during your turn.
// #1 = The from site.
// #2 = The consequences.
// @example ("HopInternationalDraughtsStyle")

(define "HopInternationalDraughtsStyle"
    (move Hop 
        #1 
        Diagonal 
        (between 
            if:(and 
                (not (is In (between) (sites ToClear))) 
                ("IsEnemyAt" (between))
            )
            (apply (remove (between) at:EndOfTurn))
        ) 
        (to if:(is Empty (to))) 
        #2
    )
)

// Common/res/def/rules/play/moves/hop/HopOnlyCounters.def
// Defines a hop move in the specified directions (by default Adjacent) over an enemy counter to an empty site. The enemy counter is removed.
// #1 = The from site.
// #2 = The direction of the hop.
// #3 = The consequences.
// @example ("HopOnlyCounters" (from (last To)) (directions {FR FL}))

(define "HopOnlyCounters"
    (move Hop 
        #1 
        #2 
        (between 
            if:("IsPieceAt" "Counter" Next (between))
            (apply (remove (between)))
        ) 
        (to if:(is Empty (to))) 
        #3
    )
)

// Common/res/def/rules/play/moves/hop/HopOrthogonalCapture.def
// Defines a hop move in all the orthogonal directions over an enemy to an empty site. The enemy piece is removed.
// @example ("HopOrthogonalCapture")

(define "HopOrthogonalCapture" 
    (move Hop 
        Orthogonal
        (between 
            if:("IsEnemyAt" (between)) 
            (apply (remove (between)))
        )
        (to if:(is Empty (to)))
    )
)

// Common/res/def/rules/play/moves/hop/HopOrthogonalSequenceCapture.def
// Defines a sequence of hop move in all the orthogonal directions over an enemy to an empty site. 
//The enemy pieces are removed.
// #1 = Maximum distance before the hop [0].
// #2 = Maximum distance after the hop [0].
// #3 = When to perform the capture (immediately or at the end of the turn) [immediately].
// @example ("HopOrthogonalSequenceCapture")
// @example ("HopOrthogonalSequenceCapture" before:(count Rows) after:(count Rows) at:EndOfTurn)

(define "HopOrthogonalSequenceCapture" 
    (move Hop
        Orthogonal
        (between 
            #1
            #2
            if:("IsEnemyAt" (between)) 
            (apply (remove (between) #3))
        )
        (to if:(is Empty (to)))
        (then 
            (if (can Move 
                    (hop 
                        (from (last To)) 
                        Orthogonal
                        (between 
                            #1
                            #2
                            if:(and 
                                (not (is In (between) (sites ToClear))) 
                                ("IsEnemyAt" (between))
                            )
                        )
                        (to if:(is Empty (to)))
                    )
                ) 
                (moveAgain)
            )
        )
    )
)

// Common/res/def/rules/play/moves/hop/HopOrthogonalSequenceCaptureAgain.def
// Defines a sequence of hop move in all the orthogonal directions over an enemy to an empty site from the last \`\`to'' location of the previous move. 
// The enemy pieces are removed.
// #1 = Maximum distance before the hop [0].
// #2 = Maximum distance after the hop [0].
// #3 = When to perform the capture (immediately or at the end of the turn) [immediately].
// @example ("HopOrthogonalSequenceCaptureAgain")
// @example ("HopOrthogonalSequenceCaptureAgain" before:(count Rows) after:(count Rows) at:EndOfTurn)

(define "HopOrthogonalSequenceCaptureAgain" 
    (move Hop
        (from (last To)) 
        Orthogonal
        (between 
            #1
            #2
            if:(and (not (is In (between) (sites ToClear))) ("IsEnemyAt" (between))) 
            (apply (remove (between) #3))
        )
        (to if:(is Empty (to)))
        (then 
            (if (can Move 
                    (hop 
                        (from (last To))
                        Orthogonal 
                        (between
                            #1
                            #2
                            if:(and
                                (not (is In (between) (sites ToClear))) 
                                ("IsEnemyAt" (between))
                            )
                        )
                        (to if:(is Empty (to)))
                    )
                ) 
                (moveAgain)
            )
        )
    )
)

// Common/res/def/rules/play/moves/hop/HopRotationalCapture.def
// Defines a hop move in all the rotational directions over an enemy to an empty site. The enemy piece is removed.
// @example ("HopRotationalCapture")

(define "HopRotationalCapture" 
    (move Hop 
        Rotational
        (between 
            if:("IsEnemyAt" (between)) 
            (apply (remove (between)))
        )
        (to if:(is Empty (to)))
    )
)

// Common/res/def/rules/play/moves/hop/HopRotationalSequenceCapture.def
// Defines a sequence of hop move in all the rotational directions over an enemy to an empty site. 
// The enemy pieces are removed.
// #1 = Maximum distance before the hop [0].
// #2 = Maximum distance after the hop [0].
// #3 = When to perform the capture (immediately or at the end of the turn) [immediately].
// @example ("HopRotationalSequenceCapture")

(define "HopRotationalSequenceCapture" 
    (move Hop
        Rotational
        (between 
            #1
            #2
            if:("IsEnemyAt" (between)) 
            (apply (remove (between) #3))
        )
        (to if:(is Empty (to)))
        (then 
            (if (can Move 
                    (hop 
                        (from (last To)) 
                        Rotational
                        (between 
                            #1
                            #2
                            if:(and 
                                (not (is In (between) (sites ToClear))) 
                                ("IsEnemyAt" (between))
                            )
                        )
                        (to if:(is Empty (to)))
                    )
                ) 
                (moveAgain)
            )
        )
    )
)

// Common/res/def/rules/play/moves/hop/HopRotationalSequenceCaptureAgain.def
// Defines a sequence of hop move in all the rotational directions over an enemy to an empty site from the last \`\`to'' location of the previous move. 
// The enemy pieces are removed.
// #1 = Maximum distance before the hop [0].
// #2 = Maximum distance after the hop [0].
// #3 = When to perform the capture (immediately or at the end of the turn) [immediately].
// @example ("HopRotationalSequenceCaptureAgain")

(define "HopRotationalSequenceCaptureAgain" 
    (move Hop
        (from (last To)) 
        Rotational
        (between 
            #1
            #2
            if:(and (not (is In (between) (sites ToClear))) ("IsEnemyAt" (between))) 
            (apply (remove (between) #3))
        )
        (to if:(is Empty (to)))
        (then 
            (if (can Move 
                    (hop 
                        (from (last To))
                        Rotational 
                        (between
                            #1
                            #2
                            if:(and 
                                (not (is In (between) (sites ToClear))) 
                                ("IsEnemyAt" (between))
                            )
                        )
                        (to if:(is Empty (to)))
                    )
                ) 
                (moveAgain)
            )
        )
    )
)

// Common/res/def/rules/play/moves/hop/HopSequenceCapture.def
// Defines a sequence of hop move in all the adjacent directions over an enemy to an empty site. 
// The enemy pieces are removed.
// #1 = Maximum distance before the hop [0].
// #2 = Maximum distance after the hop [0].
// #3 = When to perform the capture (immediately or at the end of the turn) [immediately].
// #4 = Moves to perform when the sequence cannot continue.
// @example ("HopSequenceCapture")
// @example ("HopSequenceCapture" before:(count Rows) after:(count Rows) at:EndOfTurn)

(define "HopSequenceCapture" 
    (move Hop
        (between 
            #1
            #2
            if:("IsEnemyAt" (between)) 
            (apply (remove (between) #3))
        )
        (to if:(is Empty (to)))
        (then 
            (if (can Move 
                    (hop 
                        (from (last To)) 
                        (between 
                            #1
                            #2
                            if:(and 
                                (not (is In (between) (sites ToClear))) 
                                ("IsEnemyAt" (between))
                            )
                        )
                        (to if:(is Empty (to)))
                    )
                ) 
                (moveAgain)
                #4
            )
        )
    )
)

// Common/res/def/rules/play/moves/hop/HopSequenceCaptureAgain.def
// Defines a sequence of hop move in all the adjacent directions over an enemy to an empty site from the last \`\`to'' location of the previous move. 
// The enemy pieces are removed.
// #1 = Maximum distance before the hop [0].
// #2 = Maximum distance after the hop [0].
// #3 = When to perform the capture (immediately or at the end of the turn) [immediately].
// #4 = Moves to perform when the sequence cannot continue.
// @example ("HopSequenceCaptureAgain")
// @example ("HopSequenceCaptureAgain" before:(count Rows) after:(count Rows) at:EndOfTurn)

(define "HopSequenceCaptureAgain" 
    (move Hop
        (from (last To)) 
        (between
            #1
            #2
            if:(and (not (is In (between) (sites ToClear))) ("IsEnemyAt" (between)))
            (apply (remove (between) #3))
        )
        (to if:(is Empty (to)))
        (then 
            (if (can Move 
                    (hop 
                        (from (last To)) 
                        (between 
                            #1
                            #2
                            if:(and
                                (not (is In (between) (sites ToClear))) 
                                ("IsEnemyAt" (between))
                            ) 
                        )
                        (to if:(is Empty (to)))
                    )
                ) 
                (moveAgain)
                #4
            )
        )
    )
)

// Common/res/def/rules/play/moves/hop/HopStackEnemyCaptureTop.def
// Defines a hop move in all the directions specified (by default Adjacent) over a stack with on top an enemy to an empty site. The enemy piece is moved to the top of the jumping stack.
// #1 = The from site.
// #2 = Directions of the hop.
// #3 = The consequences.
// @example ("HopStackEnemyCaptureTop")

(define "HopStackEnemyCaptureTop"
    (move Hop 
        #1
        #2 
        (between if:("IsEnemyAt" (between)) (apply (fromTo (from (between)) (to))))  	
        (to if:(and 
                (is In (from) (sites Occupied by:Mover)) 
                (is Empty (to))
            )
        )
        stack:True
        #3
    )
)

// Common/res/def/rules/play/moves/hop/HopStackEnemyCaptureTopDistance.def
// Defines a hop move in all the directions specified (by default Adjacent) over a stack with on top an enemy to an empty site at any distance. The enemy piece is moved to the top of the jumping stack.
// #1 = The from site.
// #2 = Directions of the hop.
// #3 = The consequences.
// @example ("HopStackEnemyCaptureTopDistance")

(define "HopStackEnemyCaptureTopDistance"
    (move Hop 
        #1
        #2 
        (between 
            before:(count Rows)
            after:(count Rows)
            if:("IsEnemyAt" (between)) (apply (fromTo (from (between)) (to)))
        )  	
        (to if:(and 
                (is In (from) (sites Occupied by:Mover)) 
                (is Empty (to))
            )
        )
        stack:True
        #3
    )
)

// Common/res/def/rules/play/moves/leap/LeapCapture.def
// Defines a leap move to empty or enemy sites. The enemy pieces are removed.
// #1 = The walk.
// #2 = Consequences of the capture effect.
// #3 = The consequences.
// @example ("LeapCapture" "KnightWalk")

(define "LeapCapture"
    (move
        Leap 
        #1
        (to 
            if:(not ("IsFriendAt" (to))) 
            (apply 
                (if ("IsEnemyAt" (to)) 
                    (remove 
                        (to) 
                        #2
                    )
                )
            ) 
        ) 
        #3
    )
)

// Common/res/def/rules/play/moves/leap/LeapToEmpty.def
// Defines a leap move to an empty site.
// #1 = The walk.
// #2 = The consequences.
// @example ("LeapToEmpty" "KnightWalk")

(define "LeapToEmpty"
    (move Leap
        #1
        (to if:(is Empty (to)))
        #2
    )
)

// Common/res/def/rules/play/moves/promotion/PromoteIfReach.def
// Promote the last piece moving if this piece reached a region.
// #1 = The region.
// #2 = The name of the piece to promote to.
// #3 = The movement to allow if the piece did not reach the region (Optional).
// @example ("PromoteIfReach" (sites Next) "DoubleCounter")

(define "PromoteIfReach"
    (if (is In (last To) #1) 
        (promote (last To) (piece #2) Mover)
        #3 
    )
)

// Common/res/def/rules/play/moves/remove/RemoveAnyEnemyPiece.def
// Allows to remove one piece of the enemy player.
// #1 = The consequences.
// @example ("RemoveAnyEnemyPiece")

(define "RemoveAnyEnemyPiece"
    (move Remove (sites Occupied by:Enemy container:"Board") #1)
)

// Common/res/def/rules/play/moves/remove/RemoveAnyEnemyPieceNotInLine3.def
// Allows to remove one piece of the enemy player which is not in a line 3.
// #1 = The directions of the line (by default adjacent).
// @example ("RemoveAnyEnemyPieceNotInLine3")

(define "RemoveAnyEnemyPieceNotInLine3"
    (move Remove
        (forEach 
            (sites Occupied by:Enemy container:"Board") 
            if:(not (is Line 3 #1 through:(site)))
        )
    )
)

// Common/res/def/rules/play/moves/slide/DoubleStepForwardToEmpty.def
// Defines a forward slide move to empty sites at distance 2.
// #1 = The consequences of the moves.
// @example ("DoubleStepForwardToEmpty")

(define "DoubleStepForwardToEmpty"
    (move Slide 
        Forward 
        (between (exact 2) if:(is Empty (between))) 
        (to if:(is Empty (to))) 
        #1
    ) 
)

// Common/res/def/rules/play/moves/slide/SlideCapture.def
// Defines a slide move to capture an enemy piece.
// #1 = Directions of the slide.
// #2 = Between conditions to specify (by default sliding on empty sites).
// #3 = Consequences of the capture effect.
// #4 = The consequences of the moves.
// @example ("SlideCapture" Orthogonal)

(define "SlideCapture"
    (move
        Slide
        #1
        #2
        (to 
            if:("IsEnemyAt" (to))  
            (apply 
                (remove 
                    (to) 
                    #3
                )
            ) 
        ) 
        #4
    ) 
)

// Common/res/def/rules/play/moves/step/StepBackwardToEmpty.def
// Defines a step move to the backward direction according to the facing direction of the piece in the 'from' location to an empty site.
// @example ("StepBackwardToEmpty")

(define "StepBackwardToEmpty"
    (move Step 
        Backward
        (to if:(is Empty (to)))
    )
)

// Common/res/def/rules/play/moves/step/StepDiagonalToEmpty.def
// Defines a step move to all the diagonal directions to an empty site.
// @example ("StepDiagonalToEmpty")

(define "StepDiagonalToEmpty"
    (move Step Diagonal (to if:(is Empty (to))))
)

// Common/res/def/rules/play/moves/step/StepForwardToEmpty.def
// Defines a step move to the forward direction according to the facing direction of the piece in the 'from' location to an empty site.
// @example ("StepForwardToEmpty")

(define "StepForwardToEmpty"
    (move Step 
        Forward
        (to if:(is Empty (to)))
    )
)

// Common/res/def/rules/play/moves/step/StepForwardsToEmpty.def
// Defines a step move to all the forwards directions according to the facing direction 
// of the piece in the \`\`from'' location to an empty site.
// @example ("StepForwardsToEmpty")

(define "StepForwardsToEmpty"
    (move Step Forwards (to if:(is Empty (to))))
)

// Common/res/def/rules/play/moves/step/StepOrthogonalToEmpty.def
// Defines a step move to all the orthogonal directions to an empty site.
// @example ("StepOrthogonalToEmpty")

(define "StepOrthogonalToEmpty"
    (move Step Orthogonal (to if:(is Empty (to))))
)

// Common/res/def/rules/play/moves/step/StepRotationalToEmpty.def
// Defines a step move to all the rotational directions to an empty site.
// @example ("StepRotationalToEmpty")

(define "StepRotationalToEmpty"
    (move Step Rotational (to if:(is Empty (to))))
)

// Common/res/def/rules/play/moves/step/StepStackToEmpty.def
// Defines a step move of a full stack to all the directions specified (adjacent by default) to an empty site.
// #1 = The direction(s) to step.
// #2 = The consequences.
// @example ("StepStackToEmpty")

(define "StepStackToEmpty"
    (move Step 
        #1 
        (to 
            if:(and 
                (is In (from) (sites Occupied by:Mover)) 
                (is Empty (to))
            )
        ) 
        stack:True
        #2
    )
)

// Common/res/def/rules/play/moves/step/StepToEmpty.def
// Defines a step move to all the directions specified (adjacent by default) to an empty site.
// #1 = The direction(s) to step.
// #2 = The consequences.
// @example ("StepToEmpty")

(define "StepToEmpty"
    (move Step
        #1
        (to if:(is Empty (to)))
        #2
    )
)

// Common/res/def/rules/play/moves/step/StepToEnemy.def
// Defines a step move to all the directions specified (adjacent by default) to a site occupied by an enemy piece. The enemy piece is removed.
// #1 = The direction(s) to step.
// #2 = The consequences.
// @example ("StepToEnemy")

(define "StepToEnemy"
    (move Step 
        #1
        (to 
            if:("IsEnemyAt" (to)) 
            (apply (remove (to)))
        )
        #2
    )
)

// Common/res/def/rules/play/moves/step/StepToNotFriend.def
// Defines a step move to all the directions specified (adjacent by default) to a site occupied by an enemy piece or an empty site. The enemy piece is removed.
// #1 = The direction(s) to step.
// #2 = The consequences.
// @example ("StepToNotFriend")

(define "StepToNotFriend"
    (move Step 
        #1
        (to 
            if:(not ("IsFriendAt" (to)))
            (apply (remove (to)))
        )
        #2
    )
)

// Common/res/def/rules/start/BeforeAfterCentreSetup.def
// Defines starting rules placing one piece on each site before and after the centre (e.g. Starting rules of Zamma).
// #1 = The name of the piece of P1.
// #2 = The name of the piece of P2.
// @example ("BeforeAfterCentreSetup" "Marker1" "Marker2")

(define "BeforeAfterCentreSetup"
    (start { 
        (place #1 (forEach (sites Board) if:(< (site) (centrePoint))))
        (place #2 (forEach (sites Board) if:(> (site) (centrePoint))))
    })
)

// Common/res/def/rules/start/BlackCellsSetup.def
// Defines starting rules placing one counter on each black cell of a square board (e.g. Starting rules of Draughts).
// #1 = The number of rows to place pieces for each player.
// @example ("BlackCellsSetup" 3)

(define "BlackCellsSetup"
    (start { 
        (place "Counter1" (difference (expand (sites Bottom) steps:(- #1 1)) (sites Phase 1)))
        (place "Counter2" (difference (expand (sites Top) steps:(- #1 1)) (sites Phase 1)))
    })
)

// Common/res/def/rules/start/BottomTopSetup.def
// Defines starting rules placing one piece on each cell of the bottom and the top rows of the board (e.g. Starting rules of Breakthrough).
// #1 = The number of rows to place pieces for each player.
// #2 = The name of the piece of P1.
// #3 = The name of the piece of P2.
// @example ("BottomTopSetup" 3 "Counter1" "Counter2")

(define "BottomTopSetup"
    (start { 
        (place #2 (expand (sites Bottom) steps:(- #1 1)))
        (place #3 (expand (sites Top) steps:(- #1 1)))
    })
)

// Common/res/def/rules/start/WhiteCellsSetup.def
// Defines starting rules placing one counter on each white cell of a square board (e.g. Starting rules of Draughts).
// #1 = The number of rows to place pieces for each player.
// @example ("WhiteCellsSetup" 3)

(define "WhiteCellsSetup"
    (start { 
        (place "Counter1" (difference (expand (sites Bottom) steps:(- #1 1)) (sites Phase 0)))
        (place "Counter2" (difference (expand (sites Top) steps:(- #1 1)) (sites Phase 0)))
    })
)

// Common/res/def/walk/DominoWalk.def
// Defines a graphics turtle walk to build a domino as a large piece.
// @example ("DominoWalk")

(define "DominoWalk"
    { {F R F R F L F L F R F R F} }
)

// Common/res/def/walk/GiraffeWalk.def
// Defines a graphics turtle walk to get the locations where can move a Chess giraffe.
// @example ("GiraffeWalk")

(define "GiraffeWalk"
    { {F F F R F F} {F F F L F F} }
)

// Common/res/def/walk/KnightWalk.def
// Defines a graphics turtle walk to get the locations where can move a Chess knight.
// @example ("KnightWalk")

(define "KnightWalk"
    { {F F R F} {F F L F} }
)

// Common/res/def/walk/LWalk.def
// Defines a graphics turtle walk to build a large L piece.
// @example ("LWalk")

(define "LWalk"
    { {L F R F F} {R F L F F} }
)

// Common/res/def/walk/TWalk.def
// Defines a graphics turtle walk to build a large T piece.
// @example ("TWalk")

(define "TWalk"
    { {F F F L F R R F F} }
)`;
