export {
  ACTION_OFF,
  ACTION_TYPES,
  ACTION_UNDEFINED,
  type Action,
  ActionAdd,
  type ActionAddOptions,
  ActionAddPlayerToTeam,
  ActionBet,
  ActionCopy,
  ActionForfeit,
  type ActionForfeitOptions,
  ActionForgetValue,
  ActionInsert,
  type ActionInsertOptions,
  ActionMove,
  ActionMoveLevelFrom,
  ActionMoveLevelFromLevelTo,
  ActionMoveLevelTo,
  ActionMoveN,
  type ActionMoveOptions,
  ActionMoveStacking,
  ActionMoveTopPiece,
  ActionNextInstance,
  ActionNoop,
  ActionNote,
  ActionPass,
  ActionPromote,
  ActionPropose,
  ActionRememberValue,
  ActionRemove,
  ActionRemoveLevel,
  ActionRemoveNonApplied,
  type ActionRemoveOptions,
  ActionRemoveTopPiece,
  ActionReset,
  ActionSelect,
  ActionSet,
  ActionSetAmount,
  ActionSetCost,
  ActionSetCount,
  ActionSetCounter,
  ActionSetDiceAllEqual,
  ActionSetHidden,
  ActionSetHiddenCount,
  ActionSetHiddenRotation,
  ActionSetHiddenState,
  ActionSetHiddenValue,
  ActionSetHiddenWhat,
  ActionSetHiddenWho,
  ActionSetInvisible,
  ActionSetMasked,
  ActionSetNextPlayer,
  ActionSetPending,
  ActionSetPhase,
  ActionSetPot,
  ActionSetRotation,
  ActionSetScore,
  ActionSetState,
  ActionSetTemp,
  ActionSetTrumpSuit,
  ActionSetValue,
  ActionSetValueOfPlayer,
  ActionSetVar,
  ActionSetVisible,
  ActionStoreStateInContext,
  ActionSubStackMove,
  ActionSwap,
  ActionToggle,
  ActionTrigger,
  type ActionType,
  ActionUpdateDice,
  ActionUseDie,
  ActionVote,
  BaseAction,
  isActionType,
  isSiteType,
  type PreviousHiddenSnapshot,
  SITE_TYPES,
  type SiteType,
} from "./action/index.js";
export {
  AI,
  AlphaBetaAI,
  type AlphaBetaAIOptions,
  BiasedPlayout,
  type BiasedPlayoutOptions,
  BigramStats,
  CentreFeature,
  CornerFeature,
  DecisionTree,
  type DecisionTreeInternal,
  type DecisionTreeLeaf,
  type DecisionTreeNode,
  DecisionTreeTrainer,
  type DecisionTreeTrainerOptions,
  type DiscoveryOptions,
  type DiscoverySample,
  defaultGeometricFeatures,
  discoverFeatures,
  type Evaluator,
  type Feature,
  FeatureSet,
  FlatMonteCarloAI,
  type FlatMonteCarloAIOptions,
  FriendlyNeighbourCountFeature,
  HeuristicPlayout,
  type HeuristicPlayoutOptions,
  HeuristicSampling,
  type HeuristicSamplingOptions,
  MASTPlayout,
  type MASTPlayoutOptions,
  MaterialEvaluator,
  MCTSAI,
  type MCTSAIOptions,
  MoveStats,
  NSTPlayout,
  type NSTPlayoutOptions,
  OnePlyNoHeuristic,
  type OnePlyNoHeuristicOptions,
  type PlayoutStrategy,
  PNSAI,
  type PNSAIOptions,
  type ProofGoal,
  RandomAI,
  RandomPlayout,
  type Relation,
  type SelectActionOptions,
  SpatialOffsetFeature,
  scoreForPlayer,
  type TrainingSample,
} from "./ai/index.js";
export type { API } from "./api.js";
export { getBuiltinDefines } from "./builtin-defines.js";
export {
  CONCEPT_NAMES,
  type ConceptName,
  ConceptSet,
  isConceptName,
} from "./concept.js";
export { Context } from "./context.js";
export {
  type BoolFn,
  type Dir,
  type DirectionsFn,
  type EndOutcome,
  type EndRule,
  EvalContext,
  type EvalFrame,
  type IntFn,
  InterpBoard,
  type MovesFn,
  OFF as EVAL_OFF,
  type RegionFn,
  resolveDirection,
  resolveDirectionGroup,
  resolveDirectionTokens,
  type Tiling,
  type TilingKind,
  HEX_TILING,
  SQUARE_TILING,
  TRI_TILING,
  hexagonMask,
  rhombusMask,
  triangleMask,
  triHexagonMask,
  triRectangleMask,
} from "./eval/index.js";
export { collectTopLevelDefines, expandDefines } from "./lud-defines.js";
export { expandRanges, expandSiteRanges } from "./lud-ranges.js";
export { applyOptions, collectDefaultOptions } from "./lud-options.js";
export { Move, type MoveInit } from "./move.js";
export { SeededRng } from "./rng.js";
export { SplitMix64 } from "./eval/split-mix64.js";
export {
  type CellView,
  type ContainerStateView,
  State,
} from "./state.js";
export {
  FlatTopology,
  type TopologyCell,
  type TopologyEdge,
  type TopologyVertex,
} from "./topology.js";
export { Trial, type TrialOptions, type TrialStatus } from "./trial.js";
// 1:1 Java→TS port path
export { play1to1 } from "./play1to1.js";
export type { Game1to1 } from "./ludemes/Game1to1.js";
