// @java Core/src/metadata/ai/Ai.java

import type { BestAgent } from "./agents/BestAgent.js";
import type { Mcts } from "./agents/mcts/Mcts.js";
import type { AlphaBeta } from "./agents/minimax/AlphaBeta.js";
import type { Heuristics } from "./heuristics/Heuristics.js";
import type { Features } from "./features/Features.js";
import type { FeatureTrees } from "./features/trees/FeatureTrees.js";

/**
 * A union type representing any agent specification that can appear in AI metadata.
 * Java: either BestAgent, Mcts, or AlphaBeta all implement Agent extends AIItem.
 */
export type Agent = BestAgent | Mcts | AlphaBeta;

/**
 * Defines metadata that can help AIs in the Ludii app to play this game at a
 * stronger level.
 *
 * @remarks Specifying AI metadata for games is not mandatory.
 *
 * @author Dennis Soemers and cambolbro
 */
export class Ai {
  // WARNING: The weird capitalisation of the class name is INTENTIONAL!
  // This makes the type name in the grammar and documentation look better,
  // as just "<ai>" instead of "<aI>".

  // -------------------------------------------------------------------------

  /** The agent */
  private readonly _agent: Agent | null;

  /** Heuristics */
  private readonly _heuristics: Heuristics | null;

  /** Automatically trained (or at least generated through some sort of automated process) heuristics */
  private readonly _trainedHeuristics: Heuristics | null;

  /** Features (could be handcrafted) */
  private readonly _features: Features | null;

  /** Automatically trained features */
  private _trainedFeatures: Features | null;

  /** Automatically trained feature trees */
  private readonly _trainedFeatureTrees: FeatureTrees | null;

  // -------------------------------------------------------------------------

  /**
   * Constructor
   * @param agent Can be used to specify the agent that is expected to
   * perform best in this game.
   * @param heuristics Heuristics to be used by Alpha-Beta agents.
   * @param trainedHeuristics Heuristics trained or otherwise generated by some
   * sort of automated process.
   * @param features Feature sets (possibly handcrafted) to be used for biasing MCTS-based agents.
   * @param trainedFeatures Automatically-trained feature sets.
   * @param trainedFeatureTrees Automatically-trained decision trees of features.
   *
   * @example (ai (bestAgent "UCT"))
   */
  constructor(
    agent: Agent | null = null,
    heuristics: Heuristics | null = null,
    trainedHeuristics: Heuristics | null = null,
    features: Features | null = null,
    trainedFeatures: Features | null = null,
    trainedFeatureTrees: FeatureTrees | null = null,
  ) {
    this._agent = agent;
    this._heuristics = heuristics;
    this._trainedHeuristics = trainedHeuristics;
    this._features = features;
    this._trainedFeatures = trainedFeatures;
    this._trainedFeatureTrees = trainedFeatureTrees;
  }

  // -------------------------------------------------------------------------

  /** @return Metadata item describing agent */
  agent(): Agent | null {
    return this._agent;
  }

  /**
   * @return Heuristics for this game (falls back to trainedHeuristics if null)
   */
  heuristics(): Heuristics | null {
    if (this._heuristics == null) return this._trainedHeuristics;
    return this._heuristics;
  }

  /**
   * @return Automatically trained / generated heuristics for this game
   */
  trainedHeuristics(): Heuristics | null {
    return this._trainedHeuristics;
  }

  /**
   * @return Features for this game (falls back to trainedFeatures if null)
   */
  features(): Features | null {
    if (this._features == null) return this._trainedFeatures;
    return this._features;
  }

  /**
   * @return Trained features for this game
   */
  trainedFeatures(): Features | null {
    return this._trainedFeatures;
  }

  /**
   * @return Trained feature trees for this game
   */
  trainedFeatureTrees(): FeatureTrees | null {
    return this._trainedFeatureTrees;
  }

  /**
   * Set the trained features
   * @param trainedFeatures
   */
  setTrainedFeatures(trainedFeatures: Features | null): void {
    this._trainedFeatures = trainedFeatures;
  }

  // -------------------------------------------------------------------------

  toString(): string {
    let sb = "    (ai\n";

    if (this._agent != null) sb += "        " + this._agent.toString() + "\n";
    if (this._heuristics != null) sb += "        " + this._heuristics.toString() + "\n";
    if (this._trainedHeuristics != null)
      sb += "        trainedHeuristics:" + this._trainedHeuristics.toString() + "\n";
    if (this._features != null) sb += "        " + this._features.toString() + "\n";
    if (this._trainedFeatures != null)
      sb += "        trainedFeatures:" + this._trainedFeatures.toString() + "\n";
    if (this._trainedFeatureTrees != null)
      sb += "        trainedFeatureTrees:" + this._trainedFeatureTrees.toString() + "\n";

    sb += "    )\n";
    return sb;
  }
}
