// @java Common/src/main/AliasesData.java

/**
 * Contains data on aliases for games, loaded from Player/res/help/Aliases.txt.
 * This file is not under version control, but can be generated by running
 * Player/player/utils/GenerateAliasesFile.java
 *
 * @java main/AliasesData.java
 * @author Dennis Soemers
 */
export class AliasesData {
  // -------------------------------------------------------------------------

  /** Path where we expect our data to be generated. @java AliasesData.RESOURCE_PATH */
  private static readonly RESOURCE_PATH = "/help/Aliases.txt";

  /** We'll only load once, and then just cache here. @java AliasesData.data */
  private static _data: AliasesData | null = null;

  // -------------------------------------------------------------------------

  /** Mapping from full game paths to lists of aliases. @java AliasesData.gameAliases */
  private readonly _gameAliases: Map<string, string[]> = new Map();

  // -------------------------------------------------------------------------

  /**
   * Constructor. Private, use static loadData() method instead.
   *
   * @java AliasesData()
   */
  private constructor() {
    // Do not instantiate: use static loadData() method instead
  }

  // -------------------------------------------------------------------------

  /**
   * @param gamePath Full game path (starting with /lud/ and ending with .lud)
   * @return List of aliases for the game (or null if no known aliases)
   *
   * @java AliasesData.aliasesForGame(String)
   */
  public aliasesForGame(gamePath: string): string[] | null {
    return this._gameAliases.get(gamePath) ?? null;
  }

  // -------------------------------------------------------------------------

  /**
   * @param gameNameInput Full game name.
   * @return List of aliases for the game (or null if no known aliases)
   *
   * @java AliasesData.aliasesForGameName(String)
   */
  public aliasesForGameName(gameNameInput: string): string[] | null {
    for (const [key, value] of this._gameAliases.entries()) {
      const pathSplit = key.split("/");
      let gameName = pathSplit[pathSplit.length - 1]!;
      gameName = gameName.substring(0, gameName.length - 4);
      if (gameName.toLowerCase() === gameNameInput) {
        return this._gameAliases.get(key) ?? null;
      }
    }
    return this._gameAliases.get(gameNameInput) ?? null;
  }

  // -------------------------------------------------------------------------

  /**
   * @return Aliases data
   *
   * @java AliasesData.loadData()
   */
  public static loadData(): AliasesData {
    if (AliasesData._data === null) {
      AliasesData._data = new AliasesData();
      // In the TS environment we cannot read the resource file directly.
      // Resource loading would need to be wired up externally if needed.
      // Mirrors the Java: if resource is null, skip silently.
    }
    return AliasesData._data;
  }

  // -------------------------------------------------------------------------

  /**
   * Load aliases from a text blob (mirrors reading lines from the resource file).
   * This method replaces the InputStream logic for use in TS environments.
   *
   * @param text Contents of Aliases.txt
   */
  public static loadFromText(text: string): AliasesData {
    const instance = new AliasesData();
    let currGame: string | null = null;

    for (const line of text.split("\n")) {
      const trimmed = line.trimEnd();
      if (trimmed.startsWith("/lud/") && trimmed.endsWith(".lud")) {
        currGame = trimmed;
      } else {
        if (currGame !== null) {
          if (!instance._gameAliases.has(currGame)) {
            instance._gameAliases.set(currGame, []);
          }
          instance._gameAliases.get(currGame)!.push(trimmed);
        }
      }
    }

    AliasesData._data = instance;
    return instance;
  }

  // -------------------------------------------------------------------------
}
