// @java Common/src/main/EditorHelpData.java

/**
 * This class contains data loaded from the Common/res/help/EditorHelp.txt file.
 *
 * This file is under version control, and can be regenerated by running the
 * main method of LudiiDocGen/main/GenerateLudiiEditorHelpFileMain.java
 *
 * @java main/EditorHelpData.java
 * @author Dennis Soemers and cambolbro
 */
export class EditorHelpData {
  /**
   * There can be only one.
   * @java EditorHelpData.SINGLETON
   */
  private static readonly SINGLETON: EditorHelpData = EditorHelpData.loadData();

  // -------------------------------------------------------------------------

  /** Path where we expect our data to be generated. @java EditorHelpData.RESOURCE_PATH */
  private static readonly RESOURCE_PATH = "/help/EditorHelp.txt";

  /**
   * Mapping from type-strings to strings. The key should be a fully qualified
   * type name such as "game.Game". The map gives the class-level documentation
   * for this type.
   * @java EditorHelpData.typeDocStrings
   */
  private readonly _typeDocStrings: Map<string, string>;

  /**
   * Mapping from type-strings to lists of strings. The key should be a fully
   * qualified type name such as "game.Game". For every constructor of this
   * type, the list will contain a line that fully describes that constructor.
   * @java EditorHelpData.constructorLines
   */
  private readonly _constructorLines: Map<string, string[]>;

  /**
   * Mapping from type-strings to lists of lists of strings.
   * @java EditorHelpData.constructorParamLines
   */
  private readonly _constructorParamLines: Map<string, string[][]>;

  /**
   * Mapping from type-strings to lists of lists of strings (examples).
   * @java EditorHelpData.constructorExampleLines
   */
  private readonly _constructorExampleLines: Map<string, string[][]>;

  /**
   * Mapping from define-names to strings.
   * @java EditorHelpData.defineDocStrings
   */
  private readonly _defineDocStrings: Map<string, string>;

  /**
   * Mapping from define-names to lists of strings (examples).
   * @java EditorHelpData.defineExampleLines
   */
  private readonly _defineExampleLines: Map<string, string[]>;

  /**
   * Mapping from type-strings to lists of strings (enum constants).
   * @java EditorHelpData.enumConstantLines
   */
  private readonly _enumConstantLines: Map<string, string[]>;

  /**
   * Mapping from Abstract/Interface type-strings to lists of strings (subclasses).
   * @java EditorHelpData.subclassDocLines
   */
  private readonly _subclassDocLines: Map<string, string[]>;

  /**
   * Mapping from type-strings to strings (@remarks documentation).
   * @java EditorHelpData.typeRemarksStrings
   */
  private readonly _typeRemarksStrings: Map<string, string>;

  /** @java EditorHelpData.trace */
  static trace = false;

  // -------------------------------------------------------------------------

  /**
   * Constructor. Private, should call the static loadData() method to instantiate.
   *
   * @java EditorHelpData(Map, Map, Map, Map, Map, Map, Map, Map, Map)
   */
  private constructor(
    typeDocStrings: Map<string, string>,
    constructorLines: Map<string, string[]>,
    constructorParamLines: Map<string, string[][]>,
    constructorExampleLines: Map<string, string[][]>,
    defineDocStrings: Map<string, string>,
    defineExampleLines: Map<string, string[]>,
    enumConstantLines: Map<string, string[]>,
    subclassDocLines: Map<string, string[]>,
    typeRemarksStrings: Map<string, string>
  ) {
    this._typeDocStrings = typeDocStrings;
    this._constructorLines = constructorLines;
    this._constructorParamLines = constructorParamLines;
    this._constructorExampleLines = constructorExampleLines;
    this._defineDocStrings = defineDocStrings;
    this._defineExampleLines = defineExampleLines;
    this._enumConstantLines = enumConstantLines;
    this._subclassDocLines = subclassDocLines;
    this._typeRemarksStrings = typeRemarksStrings;
  }

  // -------------------------------------------------------------------------

  /**
   * @return the one and only EditorHelpData object.
   *
   * @java EditorHelpData.get()
   */
  public static get(): EditorHelpData {
    return EditorHelpData.SINGLETON;
  }

  /**
   * @param type Fully qualified type name
   * @param n Which constructor do we want?
   * @return Grammar-like line describing the format of the nth constructor of given type.
   *
   * @java EditorHelpData.nthConstructorLine(String, int)
   */
  public nthConstructorLine(type: string, n: number): string {
    return this._constructorLines.get(type)![n]!;
  }

  /**
   * @param type Fully qualified type name
   * @param n Which constructor do we want?
   * @return List of strings, containing one string (javadoc comment) for every
   *   parameter of the nth constructor of given type.
   *
   * @java EditorHelpData.nthConstructorParamLines(String, int)
   */
  public nthConstructorParamLines(type: string, n: number): string[] {
    return this._constructorParamLines.get(type)![n]!;
  }

  /**
   * @param type Fully qualified type name
   * @param n Which constructor do we want?
   * @return List of strings, where each string is an example for the nth
   *   constructor of given type.
   *
   * @java EditorHelpData.nthConstructorExampleLines(String, int)
   */
  public nthConstructorExampleLines(type: string, n: number): string[] {
    return this._constructorExampleLines.get(type)![n]!;
  }

  /**
   * @param type Fully qualified type name
   * @return The number of constructors that the given type has.
   *
   * @java EditorHelpData.numConstructors(String)
   */
  public numConstructors(type: string): number {
    const lines = this._constructorLines.get(type);
    return lines === undefined ? 0 : lines.length;
  }

  /**
   * @param type Fully qualified type name (of an enum)
   * @return List of strings, each describing a single enum constant.
   *   Will be null for non-enum types.
   *
   * @java EditorHelpData.enumConstantLines(String)
   */
  public enumConstantLines(type: string): string[] | null {
    return this._enumConstantLines.get(type) ?? null;
  }

  /**
   * @param type Fully qualified type name (of an Abstract class or Interface)
   * @return List of strings, each describing a single subclass.
   *   Will be null for non-abstract types.
   *
   * @java EditorHelpData.subclassDocLines(String)
   */
  public subclassDocLines(type: string): string[] | null {
    return this._subclassDocLines.get(type) ?? null;
  }

  /**
   * @param type Fully qualified type name
   * @return Documentation for the type (i.e. class-level javadoc).
   *
   * @java EditorHelpData.typeDocString(String)
   */
  public typeDocString(type: string): string | undefined {
    return this._typeDocStrings.get(type);
  }

  /**
   * @param type Fully qualified type name
   * @return Remarks documentation for the type.
   *
   * @java EditorHelpData.typeRemarksString(String)
   */
  public typeRemarksString(type: string): string | undefined {
    return this._typeRemarksStrings.get(type);
  }

  /**
   * @param defineName Name of a define
   * @return Documentation string for the given define.
   *
   * @java EditorHelpData.defineDocString(String)
   */
  public defineDocString(defineName: string): string | undefined {
    return this._defineDocStrings.get(defineName);
  }

  /**
   * @param defineName Name of a define
   * @return List of example lines for the given define.
   *
   * @java EditorHelpData.defineExampleLines(String)
   */
  public defineExampleLines(defineName: string): string[] | undefined {
    return this._defineExampleLines.get(defineName);
  }

  // -------------------------------------------------------------------------

  /**
   * @return Loads the help data for the Ludii editor from the resource file.
   *
   * @java EditorHelpData.loadData()
   */
  private static loadData(): EditorHelpData {
    const typeDocStrings = new Map<string, string>();
    const constructorLines = new Map<string, string[]>();
    const constructorParamLines = new Map<string, string[][]>();
    const constructorExampleLines = new Map<string, string[][]>();
    const defineDocStrings = new Map<string, string>();
    const defineExampleLines = new Map<string, string[]>();
    const enumConstantLines = new Map<string, string[]>();
    const subclassDocLines = new Map<string, string[]>();
    const typeRemarksStrings = new Map<string, string>();

    // In the TS environment we cannot read the resource file directly.
    // Resource loading would need to be wired up externally if needed.
    // Mirrors the Java: if resource is null, return empty maps.

    return new EditorHelpData(
      typeDocStrings,
      constructorLines,
      constructorParamLines,
      constructorExampleLines,
      defineDocStrings,
      defineExampleLines,
      enumConstantLines,
      subclassDocLines,
      typeRemarksStrings
    );
  }

  /**
   * Load help data from a text blob (replaces InputStream logic for TS).
   * Mirrors the line-by-line reading from the resource file.
   *
   * @param text Contents of EditorHelp.txt
   */
  public static loadFromText(text: string): EditorHelpData {
    const typeDocStrings = new Map<string, string>();
    const constructorLines = new Map<string, string[]>();
    const constructorParamLines = new Map<string, string[][]>();
    const constructorExampleLines = new Map<string, string[][]>();
    const defineDocStrings = new Map<string, string>();
    const defineExampleLines = new Map<string, string[]>();
    const enumConstantLines = new Map<string, string[]>();
    const typeRemarksStrings = new Map<string, string>();

    // In this map we'll just collect the fully qualified names of subclasses.
    const subclasses = new Map<string, string[]>();

    let currType: string | null = null;
    let currConstructor = -1;
    let currDefine: string | null = null;

    for (const line of text.split("\n")) {
      const trimmed = line.trimEnd();

      if (trimmed.startsWith("TYPE: ")) {
        currType = trimmed.substring("TYPE: ".length);
        constructorLines.set(currType, []);
        constructorParamLines.set(currType, []);
        constructorExampleLines.set(currType, []);
        currConstructor = -1;
      } else if (trimmed.startsWith("TYPE JAVADOC: ")) {
        if (currType !== null) {
          typeDocStrings.set(currType, trimmed.substring("TYPE JAVADOC: ".length));
        }
      } else if (trimmed === "NEW CTOR") {
        ++currConstructor;
        if (currType !== null) {
          constructorParamLines.get(currType)!.push([]);
          constructorExampleLines.get(currType)!.push([]);
        }
      } else if (trimmed.startsWith("PARAM JAVADOC: ")) {
        if (currType !== null) {
          constructorParamLines.get(currType)![currConstructor]!.push(trimmed.substring("PARAM JAVADOC: ".length));
        }
      } else if (trimmed.startsWith("EXAMPLE: ")) {
        if (currType !== null) {
          constructorExampleLines.get(currType)![currConstructor]!.push(trimmed.substring("EXAMPLE: ".length));
        }
      } else if (trimmed.startsWith("DEFINE: ")) {
        currDefine = trimmed.substring("DEFINE: ".length);
        defineExampleLines.set(currDefine, []);
      } else if (trimmed.startsWith("DEFINE JAVADOC: ")) {
        if (currDefine !== null) {
          defineDocStrings.set(currDefine, trimmed.substring("DEFINE JAVADOC: ".length));
        }
      } else if (trimmed.startsWith("DEFINE EXAMPLE: ")) {
        if (currDefine !== null) {
          defineExampleLines.get(currDefine)!.push(trimmed.substring("DEFINE EXAMPLE: ".length));
        }
      } else if (trimmed.startsWith("CONST JAVADOC: ")) {
        if (currType !== null) {
          if (!enumConstantLines.has(currType)) {
            enumConstantLines.set(currType, []);
          }
          enumConstantLines.get(currType)!.push(trimmed.substring("CONST JAVADOC: ".length));
        }
      } else if (trimmed.startsWith("SUBCLASS: ")) {
        if (currType !== null) {
          if (!subclasses.has(currType)) {
            subclasses.set(currType, []);
          }
          subclasses.get(currType)!.push(trimmed.substring("SUBCLASS: ".length));
        }
      } else if (trimmed.startsWith("REMARKS: ")) {
        if (currType !== null) {
          typeRemarksStrings.set(currType, trimmed.substring("REMARKS: ".length));
        }
      } else {
        if (currType !== null) {
          constructorLines.get(currType)!.push(trimmed);
        }
      }
    }

    // Populate our map of subclass javadoc lines for abstract types
    const subclassDocLines = new Map<string, string[]>();
    for (const [abstractType, subclassTypes] of subclasses.entries()) {
      const docLines: string[] = [];
      for (const subclassType of subclassTypes) {
        let typeDoc = typeDocStrings.get(subclassType);
        if (typeDoc === undefined) {
          typeDoc = "";
          if (EditorHelpData.trace) {
            console.error("WARNING: no type doc for subclass " + subclassType + " of abstract type " + abstractType + "!");
          }
        }
        docLines.push("<" + subclassType + "> : " + typeDoc);
      }
      subclassDocLines.set(abstractType, docLines);
    }

    return new EditorHelpData(
      typeDocStrings,
      constructorLines,
      constructorParamLines,
      constructorExampleLines,
      defineDocStrings,
      defineExampleLines,
      enumConstantLines,
      subclassDocLines,
      typeRemarksStrings
    );
  }

  // -------------------------------------------------------------------------
}
