// @java Common/src/main/GameNames.java

/**
 * Game Names.
 *
 * @java main/GameNames.java
 * @author Matthew.Stephenson
 */

/** A single game name entry (mirrors an enum constant). */
interface GameNameEntry {
  readonly ludName: string;
  readonly nativeName: string;
  readonly aliases: string[];
}

function entry(ludName: string, nativeName: string, aliases: string | string[]): GameNameEntry {
  return {
    ludName,
    nativeName,
    aliases: typeof aliases === "string" ? [aliases] : aliases,
  };
}

// @java GameNames enum constants
export const GameNames = {
  GAME_War: entry("War", "", ""),
  GAME_Chopsticks: entry("Chopsticks", "", ""),
  GAME_RockPaperScissors: entry("Rock-Paper-Scissors", "", ""),
  GAME_Nim: entry("Nim", "", ""),
  GAME_Bricks: entry("Bricks", "", ""),
  GAME_FillAPix: entry("Fill A Pix", "", ""),
  GAME_Futoshiki: entry("Futoshiki", "", ""),
  GAME_Hashiwokakero: entry("Hashiwokakero", "", ""),
  GAME_InshinoHeya: entry("Inshi no Heya", "", ""),
  GAME_Juosan: entry("Juosan", "", ""),
  GAME_Kakuro: entry("Kakuro", "", ""),
  GAME_KillerSudoku: entry("Killer Sudoku", "", ""),
  GAME_LatinSquare: entry("Latin Square", "", ""),
  GAME_MagicHexagon: entry("Magic Hexagon", "", ""),
  GAME_MagicSquare: entry("Magic Square", "", ""),
  GAME_NQueens: entry("N Queens", "", ""),
  GAME_Nawabari: entry("Nawabari", "", ""),
  GAME_Slitherlink: entry("Slitherlink", "", ""),
  GAME_Squaro: entry("Squaro", "", ""),
  GAME_Sudoku: entry("Sudoku", "", ""),
  GAME_Takuzu: entry("Takuzu", "", ""),
  GAME_ChessPuzzle: entry("Chess Puzzle", "", ""),
  GAME_Insanity: entry("Insanity", "", ""),
  GAME_KnightsTour: entry("Knight's Tour", "", ""),
  GAME_NPuzzles: entry("N Puzzles", "", ""),
  GAME_PegSolitaire: entry("Peg Solitaire", "", ""),
  GAME_SafePassage: entry("Safe Passage", "", ""),
  GAME_ShogiPuzzle: entry("Shogi Puzzle", "", ""),
  GAME_TowerofHanoi: entry("Tower of Hanoi", "", ""),
  GAME_Chatauranga: entry("Chatauranga", "", ""),
  GAME_Chaturaji: entry("Chaturaji", "", ""),
  GAME_Shatranj: entry("Shatranj", "", ""),
  GAME_AmazonChess: entry("Amazon Chess", "", ""),
  GAME_CapturetheQueen: entry("Capture the Queen", "", ""),
  GAME_Chess: entry("Chess", "", ""),
  GAME_Chex: entry("Chex", "", ""),
  GAME_DoubleChess: entry("Double Chess", "", ""),
  GAME_HalfChess: entry("Half Chess", "", ""),
  GAME_HordeChess: entry("Horde Chess", "", ""),
  GAME_LoopChess: entry("Loop Chess", "", ""),
  GAME_LosAlamoschess: entry("Los Alamos chess", "", ""),
  GAME_MaharajahChess: entry("Maharajah Chess", "", ""),
  GAME_SkirmishGDL: entry("Skirmish (GDL)", "", ""),
  GAME_AtariGo: entry("Atari Go", "", ""),
  GAME_Castello: entry("Castello", "", ""),
  GAME_Fanorona: entry("Fanorona", "", ""),
  GAME_Lattaque: entry("L'attaque", "", ""),
  GAME_LudusLatrunculorum: entry("Ludus Latrunculorum", "", ""),
  GAME_Mehen: entry("Mehen", "", ""),
  GAME_Ploy: entry("Ploy", "", ""),
  GAME_PressUps: entry("Press Ups", "", ""),
  GAME_Seega: entry("Seega", "", ""),
  GAME_Surakarta: entry("Surakarta", "", ""),
  GAME_Triad: entry("Triad", "", ""),
  GAME_HasamiShogi: entry("Hasami Shogi", "", ""),
  GAME_Minishogi: entry("Minishogi", "", ""),
  GAME_Shogi: entry("Shogi", "", ""),
  GAME_TaikyokuShogi: entry("Taikyoku Shogi", "", ""),
  GAME_Janggi: entry("Janggi", "", ""),
  GAME_Manzhouqi: entry("Manzhouqi", "", ""),
  GAME_Xiangqi: entry("Xiangqi", "", ""),
  GAME_Adugo: entry("Adugo", "", ""),
  GAME_BaghChal: entry("Bagh-Chal", "", ""),
  GAME_Coyote: entry("Coyote", "", ""),
  GAME_DeCercarLaLiebre: entry("De Cercar La Liebre", "", ""),
  GAME_Demaladiviyankeliya: entry("Demala diviyan keliya", "", ""),
  GAME_DiviyanKeliya: entry("Diviyan Keliya", "", ""),
  GAME_FoxandGeese: entry("Fox and Geese", "", ""),
  GAME_GowiththeFloe: entry("Go with the Floe", "", ""),
  GAME_HatDiviyanKeliya: entry("Hat Diviyan Keliya", "", ""),
  GAME_Koapppawna: entry("Ko-app-paw-na", "", ""),
  GAME_Komikan: entry("Komikan", "", ""),
  GAME_Merimuengrimuengdo: entry("Merimueng-rimueng-do", "", ""),
  GAME_Ponchochotl: entry("Pon chochotl", "", ""),
  GAME_WolfandSheep: entry("Wolf and Sheep", "", ""),
  GAME_AleaEvangelii: entry("Alea Evangelii", "", ""),
  GAME_ArdRi: entry("ArdRi", "", ""),
  GAME_Brandub: entry("Brandub", "", ""),
  GAME_Hnefatafl: entry("Hnefatafl", "", ""),
  GAME_Tablut: entry("Tablut", "", ""),
  GAME_Tawlbwrdd: entry("Tawlbwrdd", "", ""),
  GAME_20Squares: entry("20 Squares", "", ""),
  GAME_58Holes: entry("58 Holes", "", ""),
  GAME_RoyalGameofUr: entry("Royal Game of Ur", "", ""),
  GAME_Senet: entry("Senet", "", ""),
  GAME_XIIScripta: entry("XII Scripta", "", ""),
  GAME_Camelot: entry("Camelot", "", ""),
  GAME_ChineseCheckers: entry("Chinese Checkers", "", ""),
  GAME_Grasshopper: entry("Grasshopper", "", ""),
  GAME_Halma: entry("Halma", "", ""),
  GAME_OPatKono: entry("O-Pat-Kono", "", ""),
  GAME_Salta: entry("Salta", "", ""),
  GAME_Arimaa: entry("Arimaa", "", ""),
  GAME_Ashtapada: entry("Ashtapada", "", ""),
  GAME_BreakThrough: entry("BreakThrough", "", ""),
  GAME_Conspirateurs: entry("Conspirateurs", "", ""),
  GAME_GameoftheGoose: entry("Game of the Goose", "", ""),
  GAME_GyanChaupar: entry("Gyan Chaupar", "", ""),
  GAME_Jungle: entry("Jungle", "", ""),
  GAME_KnightThrough: entry("KnightThrough", "", ""),
  GAME_Pachisi: entry("Pachisi", "", ""),
  GAME_Sneakthrough: entry("Sneakthrough", "", ""),
  GAME_Amazons: entry("Amazons", "", ""),
  GAME_BlueNile: entry("Blue Nile", "", ""),
  GAME_Contagion: entry("Contagion", "", ""),
  GAME_FrenchMilitaryGame: entry("French Military Game", "", ""),
  GAME_Horseshoe: entry("Horseshoe", "", ""),
  GAME_LGame: entry("L Game", "", ""),
  GAME_Madelinette: entry("Madelinette", "", ""),
  GAME_MuTorere: entry("Mu Torere", "", ""),
  GAME_NoGo: entry("NoGo", "", ""),
  GAME_QuantumLeap: entry("Quantum Leap", "", ""),
  GAME_Snowpaque: entry("Snowpaque", "", ""),
  GAME_Spots: entry("Spots", "", ""),
  GAME_Susan: entry("Susan", "", ""),
  GAME_Tron: entry("Tron", "", ""),
  GAME_Chameleon: entry("Chameleon", "", ""),
  GAME_Cross: entry("Cross", "", ""),
  GAME_Gonnect: entry("Gonnect", "", ""),
  GAME_Havannah: entry("Havannah", "", ""),
  GAME_Hex: entry("Hex", "", ""),
  GAME_Trax: entry("Trax", "", ""),
  GAME_YHex: entry("Y (Hex)", "", ""),
  GAME_FeedtheDucks: entry("Feed the Ducks", "", ""),
  GAME_Groups: entry("Groups", "", ""),
  GAME_LinesofAction: entry("Lines of Action", "", ""),
  GAME_Manalath: entry("Manalath", "", ""),
  GAME_Odd: entry("Odd", "", ""),
  GAME_Omega: entry("Omega", "", ""),
  GAME_Achi: entry("Achi", "", ""),
  GAME_AllQueensChess: entry("All Queens Chess", "", ""),
  GAME_Andantino: entry("Andantino", "", ""),
  GAME_Connect4: entry("Connect 4", "", ""),
  GAME_Connect6: entry("Connect6", "", ""),
  GAME_DaiHasamiShogi: entry("Dai Hasami Shogi", "", ""),
  GAME_Dala: entry("Dala", "", ""),
  GAME_Dra: entry("Dra", "", ""),
  GAME_FiveMensMorris: entry("Five Men's Morris", "", ""),
  GAME_Gomoku: entry("Gomoku", "", ""),
  GAME_NineMensMorris: entry("Nine Men's Morris", "", ""),
  GAME_Pentalath: entry("Pentalath", "", ""),
  GAME_Picaria: entry("Picaria", "", ""),
  GAME_PushingmeXO: entry("Pushing me XO", "", ""),
  GAME_RoundMerels: entry("Round Merels", "", ""),
  GAME_Shisima: entry("Shisima", "", ""),
  GAME_SixMensMorris: entry("Six Men's Morris", "", ""),
  GAME_Spline: entry("Spline", "", ""),
  GAME_Squava: entry("Squava", "", ""),
  GAME_TantFant: entry("Tant Fant", "", ""),
  GAME_ThreeMensMorris: entry("Three Men's Morris", "", ""),
  GAME_TicTacFour: entry("Tic-Tac-Four", "", ""),
  GAME_TicTacMo: entry("Tic-Tac-Mo", "", ""),
  GAME_TicTacToe: entry("Tic-Tac-Toe", "", ""),
  GAME_TwelveMensMorris: entry("Twelve Men's Morris", "", ""),
  GAME_Yavalade: entry("Yavalade", "", ""),
  GAME_Yavalanchor: entry("Yavalanchor", "", ""),
  GAME_Yavalath: entry("Yavalath", "", ""),
  GAME_Kensington: entry("Kensington", "", ""),
  GAME_Ataxx: entry("Ataxx", "", ""),
  GAME_DotsandBoxes: entry("Dots and Boxes", "", ""),
  GAME_Go: entry("Go", "", ""),
  GAME_Lotus: entry("Lotus", "", ""),
  GAME_Reversi: entry("Reversi", "", ""),
  GAME_Alquerque: entry("Alquerque", "", ""),
  GAME_HewakamKeliya: entry("Hewakam Keliya", "", ""),
  GAME_Kharbaga: entry("Kharbaga", "", ""),
  GAME_KotuEllima: entry("Kotu Ellima", "", ""),
  GAME_MogulPutthan: entry("Mogul Putt'han", "", ""),
  GAME_Peralikatuma: entry("Peralikatuma", "", ""),
  GAME_Terhuchu: entry("Terhuchu", "", ""),
  GAME_Tuknanavuhpi: entry("Tuknanavuhpi", "", ""),
  GAME_Zamma: entry("Zamma", "", ""),
  GAME_BrazilianDraughts: entry("Brazilian Draughts", "", ""),
  GAME_CanadianDraughts: entry("Canadian Draughts", "", ""),
  GAME_Dama: entry("Dama", "", ""),
  GAME_EnglishDraughts: entry("English Draughts", "", ""),
  GAME_HexDame: entry("HexDame", "", ""),
  GAME_InternationalDraughts: entry("International Draughts", "", ""),
  GAME_Lasca: entry("Lasca", "", ""),
  GAME_Awithlaknannai: entry("Awithlaknannai", "", ""),
  GAME_Dashguti: entry("Dash-guti", "", ""),
  GAME_EgaraGuti: entry("Egara Guti", "", ""),
  GAME_Felli: entry("Felli", "", ""),
  GAME_Golekuish: entry("Gol-ekuish", "", ""),
  GAME_Konane: entry("Konane", "", ""),
  GAME_LauKataKati: entry("Lau Kata Kati", "", ""),
  GAME_NeiPatKono: entry("Nei-Pat-Kono", "", ""),
  GAME_Pretwa: entry("Pretwa", "", ""),
  GAME_BaokiarabuZanzibar1: entry("Bao ki arabu (Zanzibar 1)", "", ""),
  GAME_BaokiarabuZanzibar2: entry("Bao ki arabu (Zanzibar 2)", "", ""),
  GAME_Hawalis: entry("Hawalis", "", ""),
  GAME_HusDamara: entry("Hus (Damara)", "", ""),
  GAME_Mefuvha: entry("Mefuvha", "", ""),
  GAME_MuvalavalaB: entry("Muvalavala B", "", ""),
  GAME_OwelaBenguela: entry("Owela (Benguela)", "", ""),
  GAME_Akookwe: entry("Ako okwe", "", ""),
  GAME_AwliOnnamOttjin: entry("Aw-li On-nam Ot-tjin", "", ""),
  GAME_Bosh: entry("Bosh", "", ""),
  GAME_Dabuda: entry("Dabuda", "", ""),
  GAME_DasBohnenspiel: entry("Das Bohnenspiel", "", ""),
  GAME_EnGehe: entry("En Gehe", "", ""),
  GAME_EnglishWariStLucia: entry("English Wari (St. Lucia)", "", ""),
  GAME_FrenchWari: entry("French Wari", "", ""),
  GAME_Halusa: entry("Halusa", "", ""),
  GAME_Kalah: entry("Kalah", "", ""),
  GAME_Kara: entry("Kara", "", ""),
  GAME_MangalaTurkey: entry("Mangala (Turkey)", "", ""),
  GAME_Mbangbi: entry("Mbangbi", "", ""),
  GAME_Meusueb: entry("Meusueb", "", ""),
  GAME_Oware: entry("Oware", "", ""),
  GAME_ToguzKumalak: entry("Toguz Kumalak", "", ""),
  GAME_UmelBagara: entry("Um el-Bagara", "", ""),
} as const;

export type GameNameKey = keyof typeof GameNames;
